# Disable blank issue creation
blank_issues_enabled: false
contact_links:
  - name: Upstream Sketchware Pro
    url: https://github.com/Sketchware-Pro/Sketchware-Pro
    about: This is a fork. For general Sketchware Pro questions, visit the upstream repository.