package pro.sketchware.core;

import java.util.ArrayList;
import java.util.Collections;
import java.util.HashMap;
import java.util.Map;

public class BlockSpecRegistry {

    // ===== Block Parameters: opCode -> parameter types =====
    private static final Map<String, String[]> BLOCK_PARAMS = new HashMap<>();
    // ===== Block Specs: opCode -> spec key (for StringResource lookup) =====
    private static final Map<String, String> BLOCK_SPECS = new HashMap<>();
    // ===== Event Menu Items: eventName -> menu parameter types =====
    private static final Map<String, String[]> EVENT_MENUS = new HashMap<>();
    // ===== Event Specs: eventName -> spec key (for StringResource lookup) =====
    private static final Map<String, String> EVENT_SPECS = new HashMap<>();

    static {
        initBlockParams();
        initBlockSpecs();
        initEventMenus();
        initEventSpecs();
    }

    private static void initBlockParams() {
        BLOCK_PARAMS.put("-", new String[]{"%d", "%d"});
        BLOCK_PARAMS.put("%", new String[]{"%d", "%d"});
        BLOCK_PARAMS.put("&&", new String[]{"%b", "%b"});
        BLOCK_PARAMS.put("*", new String[]{"%d", "%d"});
        BLOCK_PARAMS.put("/", new String[]{"%d", "%d"});
        BLOCK_PARAMS.put("||", new String[]{"%b", "%b"});
        BLOCK_PARAMS.put("+", new String[]{"%d", "%d"});
        BLOCK_PARAMS.put("<", new String[]{"%d", "%d"});
        BLOCK_PARAMS.put("=", new String[]{"%d", "%d"});
        BLOCK_PARAMS.put(">", new String[]{"%d", "%d"});
        BLOCK_PARAMS.put("addListInt", new String[]{"%d", "%m.listInt"});
        BLOCK_PARAMS.put("addListMap", new String[]{"%s", "%s", "%m.listMap"});
        BLOCK_PARAMS.put("addListStr", new String[]{"%s", "%m.listStr"});
        BLOCK_PARAMS.put("addMapToList", new String[]{"%m.varMap", "%m.listMap"});
        BLOCK_PARAMS.put("addSourceDirectly", new String[]{"%s.inputOnly"});
        BLOCK_PARAMS.put("adViewLoadAd", new String[]{"%m.adview"});
        BLOCK_PARAMS.put("bluetoothConnectActivateBluetooth", new String[]{"%m.bluetoothconnect"});
        BLOCK_PARAMS.put("bluetoothConnectGetPairedDevices", new String[]{"%m.bluetoothconnect", "%m.listMap"});
        BLOCK_PARAMS.put("bluetoothConnectGetRandomUuid", new String[]{"%m.bluetoothconnect"});
        BLOCK_PARAMS.put("bluetoothConnectIsBluetoothActivated", new String[]{"%m.bluetoothconnect"});
        BLOCK_PARAMS.put("bluetoothConnectIsBluetoothEnabled", new String[]{"%m.bluetoothconnect"});
        BLOCK_PARAMS.put("bluetoothConnectReadyConnection", new String[]{"%m.bluetoothconnect", "%s"});
        BLOCK_PARAMS.put("bluetoothConnectReadyConnectionToUuid", new String[]{"%m.bluetoothconnect", "%s", "%s"});
        BLOCK_PARAMS.put("bluetoothConnectSendData", new String[]{"%m.bluetoothconnect", "%s", "%s"});
        BLOCK_PARAMS.put("bluetoothConnectStartConnection", new String[]{"%m.bluetoothconnect", "%s", "%s"});
        BLOCK_PARAMS.put("bluetoothConnectStartConnectionToUuid", new String[]{"%m.bluetoothconnect", "%s", "%s", "%s"});
        BLOCK_PARAMS.put("bluetoothConnectStopConnection", new String[]{"%m.bluetoothconnect", "%s"});
        BLOCK_PARAMS.put("break", new String[]{});
        BLOCK_PARAMS.put("calendarAdd", new String[]{"%m.calendar", "%m.calendarField", "%d"});
        BLOCK_PARAMS.put("calendarDiff", new String[]{"%m.calendar", "%m.calendar"});
        BLOCK_PARAMS.put("calendarFormat", new String[]{"%m.calendar", "%s"});
        BLOCK_PARAMS.put("calendarGetNow", new String[]{"%m.calendar"});
        BLOCK_PARAMS.put("calendarGetTime", new String[]{"%m.calendar"});
        BLOCK_PARAMS.put("calendarSet", new String[]{"%m.calendar", "%m.calendarField", "%d"});
        BLOCK_PARAMS.put("calendarSetTime", new String[]{"%m.calendar", "%d"});
        BLOCK_PARAMS.put("calendarViewGetDate", new String[]{"%m.calendarview"});
        BLOCK_PARAMS.put("calendarViewSetDate", new String[]{"%m.calendarview", "%d"});
        BLOCK_PARAMS.put("calendarViewSetMinDate", new String[]{"%m.calendarview", "%d"});
        BLOCK_PARAMS.put("calnedarViewSetMaxDate", new String[]{"%m.calendarview", "%d"});
        BLOCK_PARAMS.put("camerastarttakepicture", new String[]{"%m.camera"});
        BLOCK_PARAMS.put("clearList", new String[]{"%m.list"});
        BLOCK_PARAMS.put("closeDrawer", new String[]{});
        BLOCK_PARAMS.put("containListInt", new String[]{"%m.listInt", "%d"});
        BLOCK_PARAMS.put("containListMap", new String[]{"%m.listMap", "%d", "%s"});
        BLOCK_PARAMS.put("containListStr", new String[]{"%m.listStr", "%s"});
        BLOCK_PARAMS.put("copyToClipboard", new String[]{"%s"});
        BLOCK_PARAMS.put("cropBitmapFileFromCenter", new String[]{"%s", "%s", "%d", "%d"});
        BLOCK_PARAMS.put("decreaseInt", new String[]{"%m.varInt"});
        BLOCK_PARAMS.put("deleteList", new String[]{"%d", "%m.list"});
        BLOCK_PARAMS.put("dialogCancelButton", new String[]{"%m.dialog", "%s"});
        BLOCK_PARAMS.put("dialogDismiss", new String[]{"%m.dialog"});
        BLOCK_PARAMS.put("dialogNeutralButton", new String[]{"%m.dialog", "%s"});
        BLOCK_PARAMS.put("dialogOkButton", new String[]{"%m.dialog", "%s"});
        BLOCK_PARAMS.put("dialogSetMessage", new String[]{"%m.dialog", "%s"});
        BLOCK_PARAMS.put("dialogSetTitle", new String[]{"%m.dialog", "%s"});
        BLOCK_PARAMS.put("dialogShow", new String[]{"%m.dialog"});
        BLOCK_PARAMS.put("doToast", new String[]{"%s"});
        BLOCK_PARAMS.put("else", new String[]{});
        BLOCK_PARAMS.put("false", new String[]{});
        BLOCK_PARAMS.put("fileGetData", new String[]{"%m.file", "%s"});
        BLOCK_PARAMS.put("filepickerstartpickfiles", new String[]{"%m.filepicker"});
        BLOCK_PARAMS.put("fileRemoveData", new String[]{"%m.file", "%s"});
        BLOCK_PARAMS.put("fileSetData", new String[]{"%m.file", "%s", "%s"});
        BLOCK_PARAMS.put("fileutilcopy", new String[]{"%s", "%s"});
        BLOCK_PARAMS.put("fileutildelete", new String[]{"%s"});
        BLOCK_PARAMS.put("fileutilEndsWith", new String[]{"%s", "%s"});
        BLOCK_PARAMS.put("fileutilGetLastSegmentPath", new String[]{"%s"});
        BLOCK_PARAMS.put("fileutilisdir", new String[]{"%s"});
        BLOCK_PARAMS.put("fileutilisexist", new String[]{"%s"});
        BLOCK_PARAMS.put("fileutilisfile", new String[]{"%s"});
        BLOCK_PARAMS.put("fileutillength", new String[]{"%s"});
        BLOCK_PARAMS.put("fileutillistdir", new String[]{"%s", "%m.listStr"});
        BLOCK_PARAMS.put("fileutilmakedir", new String[]{"%s"});
        BLOCK_PARAMS.put("fileutilmove", new String[]{"%s", "%s"});
        BLOCK_PARAMS.put("fileutilread", new String[]{"%s"});
        BLOCK_PARAMS.put("fileutilStartsWith", new String[]{"%s", "%s"});
        BLOCK_PARAMS.put("fileutilwrite", new String[]{"%s", "%s"});
        BLOCK_PARAMS.put("finishActivity", new String[]{});
        BLOCK_PARAMS.put("firebaseAdd", new String[]{"%m.firebase", "%s", "%m.varMap"});
        BLOCK_PARAMS.put("firebaseauthCreateUser", new String[]{"%m.firebaseauth", "%s", "%s"});
        BLOCK_PARAMS.put("firebaseauthResetPassword", new String[]{"%m.firebaseauth", "%s"});
        BLOCK_PARAMS.put("firebaseauthSignInAnonymously", new String[]{"%m.firebaseauth"});
        BLOCK_PARAMS.put("firebaseauthSignInUser", new String[]{"%m.firebaseauth", "%s", "%s"});
        BLOCK_PARAMS.put("firebaseauthGetCurrentUser", new String[]{});
        BLOCK_PARAMS.put("firebaseauthGetUid", new String[]{});
        BLOCK_PARAMS.put("firebaseauthIsLoggedIn", new String[]{});
        BLOCK_PARAMS.put("firebaseauthSignOutUser", new String[]{});
        BLOCK_PARAMS.put("firebaseDelete", new String[]{"%m.firebase", "%s"});
        BLOCK_PARAMS.put("firebaseGetChildren", new String[]{"%m.firebase", "%m.listMap"});
        BLOCK_PARAMS.put("firebaseGetPushKey", new String[]{"%m.firebase"});
        BLOCK_PARAMS.put("firebasePush", new String[]{"%m.firebase", "%m.varMap"});
        BLOCK_PARAMS.put("firebaseStartListen", new String[]{"%m.firebase"});
        BLOCK_PARAMS.put("firebaseStopListen", new String[]{"%m.firebase"});
        BLOCK_PARAMS.put("firebasestorageDelete", new String[]{"%m.firebasestorage", "%s"});
        BLOCK_PARAMS.put("firebasestorageDownloadFile", new String[]{"%m.firebasestorage", "%s", "%s"});
        BLOCK_PARAMS.put("firebasestorageUploadFile", new String[]{"%m.firebasestorage", "%s", "%s"});
        BLOCK_PARAMS.put("forever", new String[]{});
        BLOCK_PARAMS.put("getAlpha", new String[]{"%m.view"});
        BLOCK_PARAMS.put("getExternalStorageDir", new String[]{});
        BLOCK_PARAMS.put("getAtListInt", new String[]{"%d", "%m.listInt"});
        BLOCK_PARAMS.put("getAtListMap", new String[]{"%d", "%s", "%m.listMap"});
        BLOCK_PARAMS.put("getAtListStr", new String[]{"%d", "%m.listStr"});
        BLOCK_PARAMS.put("getChecked", new String[]{"%m.checkbox"});
        BLOCK_PARAMS.put("getEnable", new String[]{"%m.view"});
        BLOCK_PARAMS.put("getJpegRotate", new String[]{"%s"});
        BLOCK_PARAMS.put("getLocationX", new String[]{"%m.view"});
        BLOCK_PARAMS.put("getLocationY", new String[]{"%m.view"});
        BLOCK_PARAMS.put("getMapInList", new String[]{"%d", "%m.listMap", "%m.varMap"});
        BLOCK_PARAMS.put("getPackageDataDir", new String[]{});
        BLOCK_PARAMS.put("getPublicDir", new String[]{"%m.directoryType"});
        BLOCK_PARAMS.put("getRotate", new String[]{"%m.view"});
        BLOCK_PARAMS.put("getScaleX", new String[]{"%m.view"});
        BLOCK_PARAMS.put("getScaleY", new String[]{"%m.view"});
        BLOCK_PARAMS.put("getText", new String[]{"%m.textview"});
        BLOCK_PARAMS.put("getTranslationX", new String[]{"%m.view"});
        BLOCK_PARAMS.put("getTranslationY", new String[]{"%m.view"});
        BLOCK_PARAMS.put("gyroscopeStartListen", new String[]{"%m.gyroscope"});
        BLOCK_PARAMS.put("gyroscopeStopListen", new String[]{"%m.gyroscope"});
        BLOCK_PARAMS.put("if", new String[]{"%b"});
        BLOCK_PARAMS.put("ifElse", new String[]{"%b"});
        BLOCK_PARAMS.put("increaseInt", new String[]{"%m.varInt"});
        BLOCK_PARAMS.put("indexListInt", new String[]{"%d", "%m.listInt"});
        BLOCK_PARAMS.put("indexListStr", new String[]{"%s", "%m.listStr"});
        BLOCK_PARAMS.put("insertListInt", new String[]{"%d", "%d", "%m.listInt"});
        BLOCK_PARAMS.put("insertListMap", new String[]{"%s", "%s", "%d", "%m.listMap"});
        BLOCK_PARAMS.put("insertListStr", new String[]{"%s", "%d", "%m.listStr"});
        BLOCK_PARAMS.put("insertMapToList", new String[]{"%m.varMap", "%d", "%m.listMap"});
        BLOCK_PARAMS.put("intentGetString", new String[]{"%s"});
        BLOCK_PARAMS.put("intentPutExtra", new String[]{"%m.intent", "%s", "%s"});
        BLOCK_PARAMS.put("intentSetAction", new String[]{"%m.intent", "%m.intentAction"});
        BLOCK_PARAMS.put("intentSetData", new String[]{"%m.intent", "%s.intentData"});
        BLOCK_PARAMS.put("intentSetFlags", new String[]{"%m.intent", "%m.intentFlags"});
        BLOCK_PARAMS.put("intentSetScreen", new String[]{"%m.intent", "%m.activity"});
        BLOCK_PARAMS.put("interstitialadCreate", new String[]{"%m.interstitialad"});
        BLOCK_PARAMS.put("interstitialadLoadAd", new String[]{"%m.interstitialad"});
        BLOCK_PARAMS.put("interstitialadShow", new String[]{"%m.interstitialad"});
        BLOCK_PARAMS.put("isDrawerOpen", new String[]{});
        BLOCK_PARAMS.put("lengthList", new String[]{"%m.list"});
        BLOCK_PARAMS.put("listGetCheckedCount", new String[]{"%m.listview"});
        BLOCK_PARAMS.put("listGetCheckedPosition", new String[]{"%m.listview"});
        BLOCK_PARAMS.put("listGetCheckedPositions", new String[]{"%m.listview", "%m.listInt"});
        BLOCK_PARAMS.put("listMapToStr", new String[]{"%m.listMap"});
        BLOCK_PARAMS.put("listRefresh", new String[]{"%m.listview"});
        BLOCK_PARAMS.put("listSetCustomViewData", new String[]{"%m.listview", "%m.listMap"});
        BLOCK_PARAMS.put("listSetData", new String[]{"%m.listview", "%m.listStr"});
        BLOCK_PARAMS.put("listSetItemChecked", new String[]{"%m.listview", "%d", "%b"});
        BLOCK_PARAMS.put("listSmoothScrollTo", new String[]{"%m.listview", "%d"});
        BLOCK_PARAMS.put("locationManagerRemoveUpdates", new String[]{"%m.locationmanager"});
        BLOCK_PARAMS.put("locationManagerRequestLocationUpdates", new String[]{"%m.locationmanager", "%m.providerType", "%d", "%d"});
        BLOCK_PARAMS.put("mapClear", new String[]{"%m.varMap"});
        BLOCK_PARAMS.put("mapContainKey", new String[]{"%m.varMap", "%s"});
        BLOCK_PARAMS.put("mapCreateNew", new String[]{"%m.varMap"});
        BLOCK_PARAMS.put("mapGet", new String[]{"%m.varMap", "%s"});
        BLOCK_PARAMS.put("mapGetAllKeys", new String[]{"%m.varMap", "%m.listStr"});
        BLOCK_PARAMS.put("mapIsEmpty", new String[]{"%m.varMap"});
        BLOCK_PARAMS.put("mapPut", new String[]{"%m.varMap", "%s", "%s"});
        BLOCK_PARAMS.put("mapRemoveKey", new String[]{"%m.varMap", "%s"});
        BLOCK_PARAMS.put("mapSize", new String[]{"%m.varMap"});
        BLOCK_PARAMS.put("mapToStr", new String[]{"%m.varMap"});
        BLOCK_PARAMS.put("mapViewAddMarker", new String[]{"%m.mapview", "%s", "%d", "%d"});
        BLOCK_PARAMS.put("mapViewMoveCamera", new String[]{"%m.mapview", "%d", "%d"});
        BLOCK_PARAMS.put("mapViewSetMapType", new String[]{"%m.mapview", "%m.mapType"});
        BLOCK_PARAMS.put("mapViewSetMarkerColor", new String[]{"%m.mapview", "%s", "%m.markerColor", "%d"});
        BLOCK_PARAMS.put("mapViewSetMarkerIcon", new String[]{"%m.mapview", "%s", "%m.resource"});
        BLOCK_PARAMS.put("mapViewSetMarkerInfo", new String[]{"%m.mapview", "%s", "%s", "%s"});
        BLOCK_PARAMS.put("mapViewSetMarkerPosition", new String[]{"%m.mapview", "%s", "%d", "%d"});
        BLOCK_PARAMS.put("mapViewSetMarkerVisible", new String[]{"%m.mapview", "%s", "%b"});
        BLOCK_PARAMS.put("mapViewZoomIn", new String[]{"%m.mapview"});
        BLOCK_PARAMS.put("mapViewZoomOut", new String[]{"%m.mapview"});
        BLOCK_PARAMS.put("mapViewZoomTo", new String[]{"%m.mapview", "%d"});
        BLOCK_PARAMS.put("mathAbs", new String[]{"%d"});
        BLOCK_PARAMS.put("mathAcos", new String[]{"%d"});
        BLOCK_PARAMS.put("mathAsin", new String[]{"%d"});
        BLOCK_PARAMS.put("mathAtan", new String[]{"%d"});
        BLOCK_PARAMS.put("mathCeil", new String[]{"%d"});
        BLOCK_PARAMS.put("mathCos", new String[]{"%d"});
        BLOCK_PARAMS.put("mathE", new String[]{});
        BLOCK_PARAMS.put("mathExp", new String[]{"%d"});
        BLOCK_PARAMS.put("mathFloor", new String[]{"%d"});
        BLOCK_PARAMS.put("mathGetDip", new String[]{"%d"});
        BLOCK_PARAMS.put("mathGetDisplayHeight", new String[]{});
        BLOCK_PARAMS.put("mathGetDisplayWidth", new String[]{});
        BLOCK_PARAMS.put("mathLog", new String[]{"%d"});
        BLOCK_PARAMS.put("mathLog10", new String[]{"%d"});
        BLOCK_PARAMS.put("mathMax", new String[]{"%d", "%d"});
        BLOCK_PARAMS.put("mathMin", new String[]{"%d", "%d"});
        BLOCK_PARAMS.put("mathPi", new String[]{});
        BLOCK_PARAMS.put("mathPow", new String[]{"%d", "%d"});
        BLOCK_PARAMS.put("mathRound", new String[]{"%d"});
        BLOCK_PARAMS.put("mathSin", new String[]{"%d"});
        BLOCK_PARAMS.put("mathSqrt", new String[]{"%d"});
        BLOCK_PARAMS.put("mathTan", new String[]{"%d"});
        BLOCK_PARAMS.put("mathToDegree", new String[]{"%d"});
        BLOCK_PARAMS.put("mathToRadian", new String[]{"%d"});
        BLOCK_PARAMS.put("mediaplayerCreate", new String[]{"%m.mediaplayer", "%m.sound"});
        BLOCK_PARAMS.put("mediaplayerGetCurrent", new String[]{"%m.mediaplayer"});
        BLOCK_PARAMS.put("mediaplayerGetDuration", new String[]{"%m.mediaplayer"});
        BLOCK_PARAMS.put("mediaplayerIsLooping", new String[]{"%m.mediaplayer"});
        BLOCK_PARAMS.put("mediaplayerIsPlaying", new String[]{"%m.mediaplayer"});
        BLOCK_PARAMS.put("mediaplayerPause", new String[]{"%m.mediaplayer"});
        BLOCK_PARAMS.put("mediaplayerRelease", new String[]{"%m.mediaplayer"});
        BLOCK_PARAMS.put("mediaplayerReset", new String[]{"%m.mediaplayer"});
        BLOCK_PARAMS.put("mediaplayerSeek", new String[]{"%m.mediaplayer", "%d"});
        BLOCK_PARAMS.put("mediaplayerSetLooping", new String[]{"%m.mediaplayer", "%b"});
        BLOCK_PARAMS.put("mediaplayerStart", new String[]{"%m.mediaplayer"});
        BLOCK_PARAMS.put("notifCancel", new String[]{"%m.notification", "%d"});
        BLOCK_PARAMS.put("notifCreateChannel", new String[]{"%m.notification", "%s", "%s", "%m.notifImportance"});
        BLOCK_PARAMS.put("sqliteOpen", new String[]{"%m.sqlite", "%s"});
        BLOCK_PARAMS.put("sqliteClose", new String[]{"%m.sqlite"});
        BLOCK_PARAMS.put("sqliteExecSQL", new String[]{"%m.sqlite", "%s"});
        BLOCK_PARAMS.put("sqliteRawQuery", new String[]{"%m.sqlite", "%s"});
        BLOCK_PARAMS.put("sqliteMoveToFirst", new String[]{"%m.sqlite"});
        BLOCK_PARAMS.put("sqliteMoveToNext", new String[]{"%m.sqlite"});
        BLOCK_PARAMS.put("sqliteIsAfterLast", new String[]{"%m.sqlite"});
        BLOCK_PARAMS.put("sqliteGetString", new String[]{"%m.sqlite", "%s"});
        BLOCK_PARAMS.put("sqliteGetNumber", new String[]{"%m.sqlite", "%s"});
        BLOCK_PARAMS.put("sqliteGetCount", new String[]{"%m.sqlite"});
        BLOCK_PARAMS.put("sqliteCloseCursor", new String[]{"%m.sqlite"});
        BLOCK_PARAMS.put("sqliteIsOpen", new String[]{"%m.sqlite"});
        BLOCK_PARAMS.put("sqliteBeginTransaction", new String[]{"%m.sqlite"});
        BLOCK_PARAMS.put("sqliteSetTransactionSuccessful", new String[]{"%m.sqlite"});
        BLOCK_PARAMS.put("sqliteEndTransaction", new String[]{"%m.sqlite"});
        BLOCK_PARAMS.put("sqliteForEachRow", new String[]{"%m.sqlite"});
        BLOCK_PARAMS.put("sqliteEnableWAL", new String[]{"%m.sqlite"});
        BLOCK_PARAMS.put("sqliteCursorIsNull", new String[]{"%m.sqlite"});
        BLOCK_PARAMS.put("notifSetAutoCancel", new String[]{"%m.notification", "%b"});
        BLOCK_PARAMS.put("notifSetChannel", new String[]{"%m.notification", "%s"});
        BLOCK_PARAMS.put("notifSetClickIntent", new String[]{"%m.notification", "%m.intent"});
        BLOCK_PARAMS.put("notifSetContent", new String[]{"%m.notification", "%s"});
        BLOCK_PARAMS.put("notifSetPriority", new String[]{"%m.notification", "%m.notifPriority"});
        BLOCK_PARAMS.put("notifSetSmallIcon", new String[]{"%m.notification", "%m.resource"});
        BLOCK_PARAMS.put("notifSetTitle", new String[]{"%m.notification", "%s"});
        BLOCK_PARAMS.put("notifShow", new String[]{"%m.notification", "%d"});
        BLOCK_PARAMS.put("not", new String[]{"%b"});
        BLOCK_PARAMS.put("objectanimatorCancel", new String[]{"%m.objectanimator"});
        BLOCK_PARAMS.put("objectanimatorIsRunning", new String[]{"%m.objectanimator"});
        BLOCK_PARAMS.put("objectanimatorSetDuration", new String[]{"%m.objectanimator", "%d"});
        BLOCK_PARAMS.put("objectanimatorSetFromTo", new String[]{"%m.objectanimator", "%d", "%d"});
        BLOCK_PARAMS.put("objectanimatorSetInterpolator", new String[]{"%m.objectanimator", "%m.aniInterpolator"});
        BLOCK_PARAMS.put("objectanimatorSetProperty", new String[]{"%m.objectanimator", "%m.animatorproperty"});
        BLOCK_PARAMS.put("objectanimatorSetRepeatCount", new String[]{"%m.objectanimator", "%d"});
        BLOCK_PARAMS.put("objectanimatorSetRepeatMode", new String[]{"%m.objectanimator", "%m.aniRepeatMode"});
        BLOCK_PARAMS.put("objectanimatorSetTarget", new String[]{"%m.objectanimator", "%m.view"});
        BLOCK_PARAMS.put("objectanimatorSetValue", new String[]{"%m.objectanimator", "%d"});
        BLOCK_PARAMS.put("objectanimatorStart", new String[]{"%m.objectanimator"});
        BLOCK_PARAMS.put("openDrawer", new String[]{});
        BLOCK_PARAMS.put("progressBarSetIndeterminate", new String[]{"%m.progressbar", "%b"});
        BLOCK_PARAMS.put("random", new String[]{"%d", "%d"});
        BLOCK_PARAMS.put("repeat", new String[]{"%d"});
        BLOCK_PARAMS.put("requestFocus", new String[]{"%m.view"});
        BLOCK_PARAMS.put("requestnetworkSetHeaders", new String[]{"%m.requestnetwork", "%m.varMap"});
        BLOCK_PARAMS.put("requestnetworkSetParams", new String[]{"%m.requestnetwork", "%m.varMap", "%m.requestType"});
        BLOCK_PARAMS.put("requestnetworkStartRequestNetwork", new String[]{"%m.requestnetwork", "%m.method", "%s", "%s"});
        BLOCK_PARAMS.put("resizeBitmapFileRetainRatio", new String[]{"%s", "%s", "%d"});
        BLOCK_PARAMS.put("resizeBitmapFileToCircle", new String[]{"%s", "%s"});
        BLOCK_PARAMS.put("resizeBitmapFileToSquare", new String[]{"%s", "%s", "%d"});
        BLOCK_PARAMS.put("resizeBitmapFileWithRoundedBorder", new String[]{"%s", "%s", "%d"});
        BLOCK_PARAMS.put("rotateBitmapFile", new String[]{"%s", "%s", "%d"});
        BLOCK_PARAMS.put("scaleBitmapFile", new String[]{"%s", "%s", "%d", "%d"});
        BLOCK_PARAMS.put("seekBarGetMax", new String[]{"%m.seekbar"});
        BLOCK_PARAMS.put("seekBarGetProgress", new String[]{"%m.seekbar"});
        BLOCK_PARAMS.put("seekBarSetMax", new String[]{"%m.seekbar", "%d"});
        BLOCK_PARAMS.put("seekBarSetProgress", new String[]{"%m.seekbar", "%d"});
        BLOCK_PARAMS.put("setAlpha", new String[]{"%m.view", "%d"});
        BLOCK_PARAMS.put("setBgColor", new String[]{"%m.view", "%m.color"});
        BLOCK_PARAMS.put("setBgResource", new String[]{"%m.view", "%m.resource_bg"});
        BLOCK_PARAMS.put("setBitmapFileBrightness", new String[]{"%s", "%s", "%d"});
        BLOCK_PARAMS.put("setBitmapFileColorFilter", new String[]{"%s", "%s", "%m.color"});
        BLOCK_PARAMS.put("setBitmapFileContrast", new String[]{"%s", "%s", "%d"});
        BLOCK_PARAMS.put("setChecked", new String[]{"%m.checkbox", "%b"});
        BLOCK_PARAMS.put("setClickable", new String[]{"%m.view", "%b"});
        BLOCK_PARAMS.put("setColorFilter", new String[]{"%m.imageview", "%m.color"});
        BLOCK_PARAMS.put("setEnable", new String[]{"%m.view", "%b"});
        BLOCK_PARAMS.put("setHint", new String[]{"%m.edittext", "%s"});
        BLOCK_PARAMS.put("setHintTextColor", new String[]{"%m.edittext", "%m.color"});
        BLOCK_PARAMS.put("setImage", new String[]{"%m.imageview", "%m.resource"});
        BLOCK_PARAMS.put("setImageFilePath", new String[]{"%m.imageview", "%s"});
        BLOCK_PARAMS.put("setImageUrl", new String[]{"%m.imageview", "%s"});
        BLOCK_PARAMS.put("setListMap", new String[]{"%s", "%s", "%d", "%m.listMap"});
        BLOCK_PARAMS.put("setRotate", new String[]{"%m.view", "%d"});
        BLOCK_PARAMS.put("setScaleX", new String[]{"%m.view", "%d"});
        BLOCK_PARAMS.put("setScaleY", new String[]{"%m.view", "%d"});
        BLOCK_PARAMS.put("setText", new String[]{"%m.textview", "%s"});
        BLOCK_PARAMS.put("setTextColor", new String[]{"%m.textview", "%m.color"});
        BLOCK_PARAMS.put("setThumbResource", new String[]{"%m.switch", "%m.resource"});
        BLOCK_PARAMS.put("setTitle", new String[]{"%s"});
        BLOCK_PARAMS.put("setTrackResource", new String[]{"%m.switch", "%m.resource"});
        BLOCK_PARAMS.put("setTranslationX", new String[]{"%m.view", "%d"});
        BLOCK_PARAMS.put("setTranslationY", new String[]{"%m.view", "%d"});
        BLOCK_PARAMS.put("setTypeface", new String[]{"%m.textview", "%m.font", "%m.typeface"});
        BLOCK_PARAMS.put("setVarBoolean", new String[]{"%m.varBool", "%b"});
        BLOCK_PARAMS.put("setVarInt", new String[]{"%m.varInt", "%d"});
        BLOCK_PARAMS.put("setVarString", new String[]{"%m.varStr", "%s"});
        BLOCK_PARAMS.put("setVisible", new String[]{"%m.view", "%m.visible"});
        BLOCK_PARAMS.put("skewBitmapFile", new String[]{"%s", "%s", "%d", "%d"});
        BLOCK_PARAMS.put("soundpoolCreate", new String[]{"%m.soundpool", "%d"});
        BLOCK_PARAMS.put("soundpoolLoad", new String[]{"%m.soundpool", "%m.sound"});
        BLOCK_PARAMS.put("soundpoolStreamPlay", new String[]{"%m.soundpool", "%d", "%d"});
        BLOCK_PARAMS.put("soundpoolStreamStop", new String[]{"%m.soundpool", "%d"});
        BLOCK_PARAMS.put("speechToTextShutdown", new String[]{"%m.speechtotext"});
        BLOCK_PARAMS.put("speechToTextStartListening", new String[]{"%m.speechtotext"});
        BLOCK_PARAMS.put("speechToTextStopListening", new String[]{"%m.speechtotext"});
        BLOCK_PARAMS.put("spnGetSelection", new String[]{"%m.spinner"});
        BLOCK_PARAMS.put("spnRefresh", new String[]{"%m.spinner"});
        BLOCK_PARAMS.put("spnSetData", new String[]{"%m.spinner", "%m.listStr"});
        BLOCK_PARAMS.put("spnSetSelection", new String[]{"%m.spinner", "%d"});
        BLOCK_PARAMS.put("startActivity", new String[]{"%m.intent"});
        BLOCK_PARAMS.put("stringContains", new String[]{"%s", "%s"});
        BLOCK_PARAMS.put("stringEquals", new String[]{"%s", "%s"});
        BLOCK_PARAMS.put("stringIndex", new String[]{"%s", "%s"});
        BLOCK_PARAMS.put("stringJoin", new String[]{"%s", "%s"});
        BLOCK_PARAMS.put("stringLastIndex", new String[]{"%s", "%s"});
        BLOCK_PARAMS.put("stringLength", new String[]{"%s"});
        BLOCK_PARAMS.put("stringReplace", new String[]{"%s", "%s", "%s"});
        BLOCK_PARAMS.put("stringReplaceAll", new String[]{"%s", "%s", "%s"});
        BLOCK_PARAMS.put("stringReplaceFirst", new String[]{"%s", "%s", "%s"});
        BLOCK_PARAMS.put("stringSub", new String[]{"%s", "%d", "%d"});
        BLOCK_PARAMS.put("strToListMap", new String[]{"%s", "%m.listMap"});
        BLOCK_PARAMS.put("strToMap", new String[]{"%s", "%m.varMap"});
        BLOCK_PARAMS.put("textToSpeechIsSpeaking", new String[]{"%m.texttospeech"});
        BLOCK_PARAMS.put("textToSpeechSetPitch", new String[]{"%m.texttospeech", "%d"});
        BLOCK_PARAMS.put("textToSpeechSetSpeechRate", new String[]{"%m.texttospeech", "%d"});
        BLOCK_PARAMS.put("textToSpeechShutdown", new String[]{"%m.texttospeech"});
        BLOCK_PARAMS.put("textToSpeechSpeak", new String[]{"%m.texttospeech", "%s"});
        BLOCK_PARAMS.put("textToSpeechStop", new String[]{"%m.texttospeech"});
        BLOCK_PARAMS.put("timerAfter", new String[]{"%m.timer", "%d"});
        BLOCK_PARAMS.put("timerCancel", new String[]{"%m.timer"});
        BLOCK_PARAMS.put("timerEvery", new String[]{"%m.timer", "%d", "%d"});
        BLOCK_PARAMS.put("toLowerCase", new String[]{"%s"});
        BLOCK_PARAMS.put("toNumber", new String[]{"%s"});
        BLOCK_PARAMS.put("toString", new String[]{"%d"});
        BLOCK_PARAMS.put("toStringFormat", new String[]{"%d", "%s"});
        BLOCK_PARAMS.put("toStringWithDecimal", new String[]{"%d"});
        BLOCK_PARAMS.put("toUpperCase", new String[]{"%s"});
        BLOCK_PARAMS.put("trim", new String[]{"%s"});
        BLOCK_PARAMS.put("true", new String[]{});
        BLOCK_PARAMS.put("vibratorAction", new String[]{"%m.vibrator", "%d"});
        BLOCK_PARAMS.put("viewOnClick", new String[]{"%m.view"});
        BLOCK_PARAMS.put("webViewCanGoBack", new String[]{"%m.webview"});
        BLOCK_PARAMS.put("webViewCanGoForward", new String[]{"%m.webview"});
        BLOCK_PARAMS.put("webViewClearCache", new String[]{"%m.webview"});
        BLOCK_PARAMS.put("webViewClearHistory", new String[]{"%m.webview"});
        BLOCK_PARAMS.put("webViewGetUrl", new String[]{"%m.webview"});
        BLOCK_PARAMS.put("webViewGoBack", new String[]{"%m.webview"});
        BLOCK_PARAMS.put("webViewGoForward", new String[]{"%m.webview"});
        BLOCK_PARAMS.put("webViewLoadUrl", new String[]{"%m.webview", "%s.url"});
        BLOCK_PARAMS.put("webViewSetCacheMode", new String[]{"%m.webview", "%m.cacheMode"});
        BLOCK_PARAMS.put("webViewStopLoading", new String[]{"%m.webview"});
        BLOCK_PARAMS.put("webViewZoomIn", new String[]{"%m.webview"});
        BLOCK_PARAMS.put("webViewZoomOut", new String[]{"%m.webview"});
    }

    private static void initBlockSpecs() {
        BLOCK_SPECS.put("-", "minus");
        BLOCK_SPECS.put("%", "rest");
        BLOCK_SPECS.put("&&", "and");
        BLOCK_SPECS.put("*", "times");
        BLOCK_SPECS.put("/", "divide");
        BLOCK_SPECS.put("||", "or");
        BLOCK_SPECS.put("+", "plus");
        BLOCK_SPECS.put("<", "smaller");
        BLOCK_SPECS.put("=", "equal");
        BLOCK_SPECS.put(">", "bigger");
        BLOCK_SPECS.put("addListInt", "add_list_int");
        BLOCK_SPECS.put("addListMap", "add_list_map");
        BLOCK_SPECS.put("addListStr", "add_list_str");
        BLOCK_SPECS.put("addMapToList", "add_map_to_list");
        BLOCK_SPECS.put("addSourceDirectly", "add_source_directly");
        BLOCK_SPECS.put("adViewLoadAd", "adview_load_ad");
        BLOCK_SPECS.put("bluetoothConnectActivateBluetooth", "bluetoothconnect_activate_bluetooth");
        BLOCK_SPECS.put("bluetoothConnectGetPairedDevices", "bluetoothconnect_get_paired_devices");
        BLOCK_SPECS.put("bluetoothConnectGetRandomUuid", "bluetoothconnect_get_random_uuid");
        BLOCK_SPECS.put("bluetoothConnectIsBluetoothActivated", "bluetoothconnect_is_bluetooth_activated");
        BLOCK_SPECS.put("bluetoothConnectIsBluetoothEnabled", "bluetoothconnect_is_bluetooth_enabled");
        BLOCK_SPECS.put("bluetoothConnectReadyConnection", "bluetoothconnect_ready_connection");
        BLOCK_SPECS.put("bluetoothConnectReadyConnectionToUuid", "bluetoothconnect_ready_connection_to_uuid");
        BLOCK_SPECS.put("bluetoothConnectSendData", "bluetoothconnect_send_data");
        BLOCK_SPECS.put("bluetoothConnectStartConnection", "bluetoothconnect_start_connection");
        BLOCK_SPECS.put("bluetoothConnectStartConnectionToUuid", "bluetoothconnect_start_connection_to_uuid");
        BLOCK_SPECS.put("bluetoothConnectStopConnection", "bluetoothconnect_stop_connection");
        BLOCK_SPECS.put("break", "break");
        BLOCK_SPECS.put("calendarAdd", "calendar_add");
        BLOCK_SPECS.put("calendarDiff", "calendar_diff");
        BLOCK_SPECS.put("calendarFormat", "calendar_format");
        BLOCK_SPECS.put("calendarGetNow", "calendar_get_now");
        BLOCK_SPECS.put("calendarGetTime", "calendar_get_time");
        BLOCK_SPECS.put("calendarSet", "calendar_set");
        BLOCK_SPECS.put("calendarSetTime", "calendar_set_time");
        BLOCK_SPECS.put("calendarViewGetDate", "calendarview_get_date");
        BLOCK_SPECS.put("calendarViewSetDate", "calendarview_set_date");
        BLOCK_SPECS.put("calendarViewSetMinDate", "calendarview_set_min_date");
        BLOCK_SPECS.put("calnedarViewSetMaxDate", "calendarview_set_max_date");
        BLOCK_SPECS.put("camerastarttakepicture", "camera_start_take_picture");
        BLOCK_SPECS.put("clearList", "clear_list");
        BLOCK_SPECS.put("closeDrawer", "close_drawer");
        BLOCK_SPECS.put("containListInt", "contain_list_int");
        BLOCK_SPECS.put("containListMap", "contain_list_map");
        BLOCK_SPECS.put("containListStr", "contain_list_str");
        BLOCK_SPECS.put("copyToClipboard", "copy_to_clipboard");
        BLOCK_SPECS.put("cropBitmapFileFromCenter", "crop_bitmap_center");
        BLOCK_SPECS.put("decreaseInt", "decrease_int");
        BLOCK_SPECS.put("deleteList", "delete_list");
        BLOCK_SPECS.put("dialogCancelButton", "dialog_cancel_button");
        BLOCK_SPECS.put("dialogDismiss", "dialog_dismiss");
        BLOCK_SPECS.put("dialogNeutralButton", "dialog_neutral_button");
        BLOCK_SPECS.put("dialogOkButton", "dialog_ok_button");
        BLOCK_SPECS.put("dialogSetMessage", "dialog_set_message");
        BLOCK_SPECS.put("dialogSetTitle", "dialog_set_title");
        BLOCK_SPECS.put("dialogShow", "dialog_show");
        BLOCK_SPECS.put("doToast", "do_toast");
        BLOCK_SPECS.put("else", "else");
        BLOCK_SPECS.put("false", "false");
        BLOCK_SPECS.put("fileGetData", "file_get_data");
        BLOCK_SPECS.put("filepickerstartpickfiles", "file_picker_start_pick_files");
        BLOCK_SPECS.put("fileRemoveData", "file_remove_data");
        BLOCK_SPECS.put("fileSetData", "file_set_data");
        BLOCK_SPECS.put("fileutilcopy", "fileutil_copy");
        BLOCK_SPECS.put("fileutildelete", "fileutil_delete");
        BLOCK_SPECS.put("fileutilEndsWith", "fileutil_ends_with");
        BLOCK_SPECS.put("fileutilGetLastSegmentPath", "fileutil_get_last_segment_path");
        BLOCK_SPECS.put("fileutilisdir", "fileutil_is_dir");
        BLOCK_SPECS.put("fileutilisexist", "fileutil_is_exist");
        BLOCK_SPECS.put("fileutilisfile", "fileutil_is_file");
        BLOCK_SPECS.put("fileutillength", "fileutil_length");
        BLOCK_SPECS.put("fileutillistdir", "fileutil_list_dir");
        BLOCK_SPECS.put("fileutilmakedir", "fileutil_make_dir");
        BLOCK_SPECS.put("fileutilmove", "fileutil_move");
        BLOCK_SPECS.put("fileutilread", "fileutil_read");
        BLOCK_SPECS.put("fileutilStartsWith", "fileutil_starts_with");
        BLOCK_SPECS.put("fileutilwrite", "fileutil_write");
        BLOCK_SPECS.put("finishActivity", "finish_activity");
        BLOCK_SPECS.put("firebaseAdd", "firebase_add");
        BLOCK_SPECS.put("firebaseauthCreateUser", "firebaseauth_create_user");
        BLOCK_SPECS.put("firebaseauthGetCurrentUser", "firebaseauth_get_email");
        BLOCK_SPECS.put("firebaseauthGetUid", "firebaseauth_get_uid");
        BLOCK_SPECS.put("firebaseauthIsLoggedIn", "firebaseauth_is_logged_in");
        BLOCK_SPECS.put("firebaseauthResetPassword", "firebaseauth_reset_password");
        BLOCK_SPECS.put("firebaseauthSignInAnonymously", "firebaseauth_signin_anonymously");
        BLOCK_SPECS.put("firebaseauthSignInUser", "firebaseauth_signin_user");
        BLOCK_SPECS.put("firebaseauthSignOutUser", "firebaseauth_signout");
        BLOCK_SPECS.put("firebaseDelete", "firebase_delete");
        BLOCK_SPECS.put("firebaseGetChildren", "firebase_get_children");
        BLOCK_SPECS.put("firebaseGetPushKey", "firebase_get_key");
        BLOCK_SPECS.put("firebasePush", "firebase_push");
        BLOCK_SPECS.put("firebaseStartListen", "firebase_start_listen");
        BLOCK_SPECS.put("firebaseStopListen", "firebase_stop_listen");
        BLOCK_SPECS.put("firebasestorageDelete", "firebasestorage_delete");
        BLOCK_SPECS.put("firebasestorageDownloadFile", "firebasestorage_download_file");
        BLOCK_SPECS.put("firebasestorageUploadFile", "firebasestorage_upload_file");
        BLOCK_SPECS.put("forever", "forever");
        BLOCK_SPECS.put("getAlpha", "get_alpha");
        BLOCK_SPECS.put("getAtListInt", "get_at_list_int");
        BLOCK_SPECS.put("getAtListMap", "get_at_list_map");
        BLOCK_SPECS.put("getAtListStr", "get_at_list_str");
        BLOCK_SPECS.put("getChecked", "get_checked");
        BLOCK_SPECS.put("getEnable", "get_enable");
        BLOCK_SPECS.put("getExternalStorageDir", "get_external_storage_dir");
        BLOCK_SPECS.put("getJpegRotate", "get_jpeg_rotate");
        BLOCK_SPECS.put("getLocationX", "get_location_x");
        BLOCK_SPECS.put("getLocationY", "get_location_y");
        BLOCK_SPECS.put("getMapInList", "get_map_in_list");
        BLOCK_SPECS.put("getPackageDataDir", "get_package_data_dir");
        BLOCK_SPECS.put("getPublicDir", "get_public_dir");
        BLOCK_SPECS.put("getRotate", "get_rotate");
        BLOCK_SPECS.put("getScaleX", "get_scale_x");
        BLOCK_SPECS.put("getScaleY", "get_scale_y");
        BLOCK_SPECS.put("getText", "get_text");
        BLOCK_SPECS.put("getTranslationX", "get_translation_x");
        BLOCK_SPECS.put("getTranslationY", "get_translation_y");
        BLOCK_SPECS.put("gyroscopeStartListen", "gyroscope_start_listen");
        BLOCK_SPECS.put("gyroscopeStopListen", "gyroscope_stop_listen");
        BLOCK_SPECS.put("if", "if");
        BLOCK_SPECS.put("ifElse", "if_else");
        BLOCK_SPECS.put("increaseInt", "increase_int");
        BLOCK_SPECS.put("indexListInt", "indexof_list_int");
        BLOCK_SPECS.put("indexListStr", "indexof_list_str");
        BLOCK_SPECS.put("insertListInt", "insert_list_int");
        BLOCK_SPECS.put("insertListMap", "insert_list_map");
        BLOCK_SPECS.put("insertListStr", "insert_list_str");
        BLOCK_SPECS.put("insertMapToList", "insert_map_to_list");
        BLOCK_SPECS.put("intentGetString", "intent_get_string");
        BLOCK_SPECS.put("intentPutExtra", "intent_put_extra");
        BLOCK_SPECS.put("intentSetAction", "intent_set_action");
        BLOCK_SPECS.put("intentSetData", "intent_set_data");
        BLOCK_SPECS.put("intentSetFlags", "intent_set_flags");
        BLOCK_SPECS.put("intentSetScreen", "intent_set_screen");
        BLOCK_SPECS.put("interstitialadCreate", "interstitialad_create");
        BLOCK_SPECS.put("interstitialadLoadAd", "interstitialad_load_ad");
        BLOCK_SPECS.put("interstitialadShow", "interstitialad_show");
        BLOCK_SPECS.put("isDrawerOpen", "is_drawer_open");
        BLOCK_SPECS.put("lengthList", "length_list");
        BLOCK_SPECS.put("listGetCheckedCount", "list_get_checked_count");
        BLOCK_SPECS.put("listGetCheckedPosition", "list_get_checked_position");
        BLOCK_SPECS.put("listGetCheckedPositions", "list_get_checked_positions");
        BLOCK_SPECS.put("listMapToStr", "list_map_to_str");
        BLOCK_SPECS.put("listRefresh", "list_refresh");
        BLOCK_SPECS.put("listSetCustomViewData", "list_set_custom_view_data");
        BLOCK_SPECS.put("listSetData", "list_set_data");
        BLOCK_SPECS.put("listSetItemChecked", "list_set_item_checked");
        BLOCK_SPECS.put("listSmoothScrollTo", "list_smooth_scrollto");
        BLOCK_SPECS.put("locationManagerRemoveUpdates", "locationmanager_remove_updates");
        BLOCK_SPECS.put("locationManagerRequestLocationUpdates", "locationmanager_request_location_updates");
        BLOCK_SPECS.put("mapClear", "map_clear");
        BLOCK_SPECS.put("mapContainKey", "map_contain_key");
        BLOCK_SPECS.put("mapCreateNew", "map_create_new");
        BLOCK_SPECS.put("mapGet", "map_get");
        BLOCK_SPECS.put("mapGetAllKeys", "map_get_all_keys");
        BLOCK_SPECS.put("mapIsEmpty", "map_is_empty");
        BLOCK_SPECS.put("mapPut", "map_put");
        BLOCK_SPECS.put("mapRemoveKey", "map_remove_key");
        BLOCK_SPECS.put("mapSize", "map_size");
        BLOCK_SPECS.put("mapToStr", "map_to_str");
        BLOCK_SPECS.put("mapViewAddMarker", "mapview_add_marker");
        BLOCK_SPECS.put("mapViewMoveCamera", "mapview_move_camera");
        BLOCK_SPECS.put("mapViewSetMapType", "mapview_set_map_type");
        BLOCK_SPECS.put("mapViewSetMarkerColor", "mapview_set_marker_color");
        BLOCK_SPECS.put("mapViewSetMarkerIcon", "mapview_set_marker_icon");
        BLOCK_SPECS.put("mapViewSetMarkerInfo", "mapview_set_marker_info");
        BLOCK_SPECS.put("mapViewSetMarkerPosition", "mapview_set_marker_position");
        BLOCK_SPECS.put("mapViewSetMarkerVisible", "mapview_set_marker_visible");
        BLOCK_SPECS.put("mapViewZoomIn", "mapview_zoom_in");
        BLOCK_SPECS.put("mapViewZoomOut", "mapview_zoom_out");
        BLOCK_SPECS.put("mapViewZoomTo", "mapview_zoom_to");
        BLOCK_SPECS.put("mathAbs", "math_abs");
        BLOCK_SPECS.put("mathAcos", "math_acos");
        BLOCK_SPECS.put("mathAsin", "math_asin");
        BLOCK_SPECS.put("mathAtan", "math_atan");
        BLOCK_SPECS.put("mathCeil", "math_ceil");
        BLOCK_SPECS.put("mathCos", "math_cos");
        BLOCK_SPECS.put("mathE", "math_e");
        BLOCK_SPECS.put("mathExp", "math_exp");
        BLOCK_SPECS.put("mathFloor", "math_floor");
        BLOCK_SPECS.put("mathGetDip", "math_get_dip");
        BLOCK_SPECS.put("mathGetDisplayHeight", "math_get_display_height");
        BLOCK_SPECS.put("mathGetDisplayWidth", "math_get_display_width");
        BLOCK_SPECS.put("mathLog", "math_log");
        BLOCK_SPECS.put("mathLog10", "math_log10");
        BLOCK_SPECS.put("mathMax", "math_max");
        BLOCK_SPECS.put("mathMin", "math_min");
        BLOCK_SPECS.put("mathPi", "math_pi");
        BLOCK_SPECS.put("mathPow", "math_pow");
        BLOCK_SPECS.put("mathRound", "math_round");
        BLOCK_SPECS.put("mathSin", "math_sin");
        BLOCK_SPECS.put("mathSqrt", "math_sqrt");
        BLOCK_SPECS.put("mathTan", "math_tan");
        BLOCK_SPECS.put("mathToDegree", "math_to_degree");
        BLOCK_SPECS.put("mathToRadian", "math_to_radian");
        BLOCK_SPECS.put("mediaplayerCreate", "mediaplayer_create");
        BLOCK_SPECS.put("mediaplayerGetCurrent", "mediaplayer_get_current");
        BLOCK_SPECS.put("mediaplayerGetDuration", "mediaplayer_get_duration");
        BLOCK_SPECS.put("mediaplayerIsLooping", "mediaplayer_is_looping");
        BLOCK_SPECS.put("mediaplayerIsPlaying", "mediaplayer_is_playing");
        BLOCK_SPECS.put("mediaplayerPause", "mediaplayer_pause");
        BLOCK_SPECS.put("mediaplayerRelease", "mediaplayer_release");
        BLOCK_SPECS.put("mediaplayerReset", "mediaplayer_reset");
        BLOCK_SPECS.put("mediaplayerSeek", "mediaplayer_seek");
        BLOCK_SPECS.put("mediaplayerSetLooping", "mediaplayer_set_looping");
        BLOCK_SPECS.put("mediaplayerStart", "mediaplayer_start");
        BLOCK_SPECS.put("notifCancel", "notif_cancel");
        BLOCK_SPECS.put("notifCreateChannel", "notif_create_channel");
        BLOCK_SPECS.put("sqliteOpen", "sqlite_open");
        BLOCK_SPECS.put("sqliteClose", "sqlite_close");
        BLOCK_SPECS.put("sqliteExecSQL", "sqlite_exec_sql");
        BLOCK_SPECS.put("sqliteRawQuery", "sqlite_raw_query");
        BLOCK_SPECS.put("sqliteMoveToFirst", "sqlite_move_to_first");
        BLOCK_SPECS.put("sqliteMoveToNext", "sqlite_move_to_next");
        BLOCK_SPECS.put("sqliteIsAfterLast", "sqlite_is_after_last");
        BLOCK_SPECS.put("sqliteGetString", "sqlite_get_string");
        BLOCK_SPECS.put("sqliteGetNumber", "sqlite_get_number");
        BLOCK_SPECS.put("sqliteGetCount", "sqlite_get_count");
        BLOCK_SPECS.put("sqliteCloseCursor", "sqlite_close_cursor");
        BLOCK_SPECS.put("sqliteIsOpen", "sqlite_is_open");
        BLOCK_SPECS.put("sqliteBeginTransaction", "sqlite_begin_transaction");
        BLOCK_SPECS.put("sqliteSetTransactionSuccessful", "sqlite_set_transaction_successful");
        BLOCK_SPECS.put("sqliteEndTransaction", "sqlite_end_transaction");
        BLOCK_SPECS.put("sqliteForEachRow", "sqlite_for_each_row");
        BLOCK_SPECS.put("sqliteEnableWAL", "sqlite_enable_wal");
        BLOCK_SPECS.put("sqliteCursorIsNull", "sqlite_cursor_is_null");
        BLOCK_SPECS.put("notifSetAutoCancel", "notif_set_auto_cancel");
        BLOCK_SPECS.put("notifSetChannel", "notif_set_channel");
        BLOCK_SPECS.put("notifSetClickIntent", "notif_set_click_intent");
        BLOCK_SPECS.put("notifSetContent", "notif_set_content");
        BLOCK_SPECS.put("notifSetPriority", "notif_set_priority");
        BLOCK_SPECS.put("notifSetSmallIcon", "notif_set_small_icon");
        BLOCK_SPECS.put("notifSetTitle", "notif_set_title");
        BLOCK_SPECS.put("notifShow", "notif_show");
        BLOCK_SPECS.put("not", "not");
        BLOCK_SPECS.put("objectanimatorCancel", "objectanimator_cancel");
        BLOCK_SPECS.put("objectanimatorIsRunning", "objectanimator_is_running");
        BLOCK_SPECS.put("objectanimatorSetDuration", "objectanimator_set_duration");
        BLOCK_SPECS.put("objectanimatorSetFromTo", "objectanimator_set_from_to");
        BLOCK_SPECS.put("objectanimatorSetInterpolator", "objectanimator_set_interpolator");
        BLOCK_SPECS.put("objectanimatorSetProperty", "objectanimator_set_property");
        BLOCK_SPECS.put("objectanimatorSetRepeatCount", "objectanimator_set_repeat_count");
        BLOCK_SPECS.put("objectanimatorSetRepeatMode", "objectanimator_set_repeat_mode");
        BLOCK_SPECS.put("objectanimatorSetTarget", "objectanimator_set_target");
        BLOCK_SPECS.put("objectanimatorSetValue", "objectanimator_set_value");
        BLOCK_SPECS.put("objectanimatorStart", "objectanimator_start");
        BLOCK_SPECS.put("openDrawer", "open_drawer");
        BLOCK_SPECS.put("progressBarSetIndeterminate", "progressbar_set_indeterminate");
        BLOCK_SPECS.put("random", "random");
        BLOCK_SPECS.put("repeat", "repeat");
        BLOCK_SPECS.put("requestFocus", "request_focus");
        BLOCK_SPECS.put("requestnetworkSetHeaders", "requestnetwork_set_headers");
        BLOCK_SPECS.put("requestnetworkSetParams", "requestnetwork_set_params");
        BLOCK_SPECS.put("requestnetworkStartRequestNetwork", "requestnetwork_start_request_network");
        BLOCK_SPECS.put("resizeBitmapFileRetainRatio", "resize_bitmap_ratio");
        BLOCK_SPECS.put("resizeBitmapFileToCircle", "resize_bitmap_circle");
        BLOCK_SPECS.put("resizeBitmapFileToSquare", "resize_bitmap_square");
        BLOCK_SPECS.put("resizeBitmapFileWithRoundedBorder", "resize_bitmap_rounded");
        BLOCK_SPECS.put("rotateBitmapFile", "rotate_bitmap");
        BLOCK_SPECS.put("scaleBitmapFile", "scale_bitmap");
        BLOCK_SPECS.put("seekBarGetMax", "seekbar_get_max");
        BLOCK_SPECS.put("seekBarGetProgress", "seekbar_get_progress");
        BLOCK_SPECS.put("seekBarSetMax", "seekbar_set_max");
        BLOCK_SPECS.put("seekBarSetProgress", "seekbar_set_progress");
        BLOCK_SPECS.put("setAlpha", "set_alpha");
        BLOCK_SPECS.put("setBgColor", "set_bg_color");
        BLOCK_SPECS.put("setBgResource", "set_bg_resource");
        BLOCK_SPECS.put("setBitmapFileBrightness", "set_bitmap_brightness");
        BLOCK_SPECS.put("setBitmapFileColorFilter", "set_bitmap_color_filter");
        BLOCK_SPECS.put("setBitmapFileContrast", "set_bitmap_contrast");
        BLOCK_SPECS.put("setChecked", "set_checked");
        BLOCK_SPECS.put("setClickable", "set_clickable");
        BLOCK_SPECS.put("setColorFilter", "set_color_filter");
        BLOCK_SPECS.put("setEnable", "set_enable");
        BLOCK_SPECS.put("setHint", "set_hint");
        BLOCK_SPECS.put("setHintTextColor", "set_hint_text_color");
        BLOCK_SPECS.put("setImage", "set_image");
        BLOCK_SPECS.put("setImageFilePath", "set_image_file_path");
        BLOCK_SPECS.put("setImageUrl", "set_image_url");
        BLOCK_SPECS.put("setListMap", "set_at_list_map");
        BLOCK_SPECS.put("setRotate", "set_rotate");
        BLOCK_SPECS.put("setScaleX", "set_scale_x");
        BLOCK_SPECS.put("setScaleY", "set_scale_y");
        BLOCK_SPECS.put("setText", "set_text");
        BLOCK_SPECS.put("setTextColor", "set_text_color");
        BLOCK_SPECS.put("setThumbResource", "set_thumb_resource");
        BLOCK_SPECS.put("setTitle", "set_title");
        BLOCK_SPECS.put("setTrackResource", "set_track_resource");
        BLOCK_SPECS.put("setTranslationX", "set_translation_x");
        BLOCK_SPECS.put("setTranslationY", "set_translation_y");
        BLOCK_SPECS.put("setTypeface", "set_typeface");
        BLOCK_SPECS.put("setVarBoolean", "set_var_bool");
        BLOCK_SPECS.put("setVarInt", "set_var_int");
        BLOCK_SPECS.put("setVarString", "set_var_str");
        BLOCK_SPECS.put("setVisible", "set_visible");
        BLOCK_SPECS.put("skewBitmapFile", "skew_bitmap");
        BLOCK_SPECS.put("soundpoolCreate", "soundpool_create");
        BLOCK_SPECS.put("soundpoolLoad", "soundpool_load");
        BLOCK_SPECS.put("soundpoolStreamPlay", "soundpool_stream_play");
        BLOCK_SPECS.put("soundpoolStreamStop", "soundpool_stream_stop");
        BLOCK_SPECS.put("speechToTextShutdown", "speechtotext_shutdown");
        BLOCK_SPECS.put("speechToTextStartListening", "speechtotext_start_listening");
        BLOCK_SPECS.put("speechToTextStopListening", "speechtotext_stop_listening");
        BLOCK_SPECS.put("spnGetSelection", "spn_get_selection");
        BLOCK_SPECS.put("spnRefresh", "spn_refresh");
        BLOCK_SPECS.put("spnSetData", "spn_set_data");
        BLOCK_SPECS.put("spnSetSelection", "spn_set_selection");
        BLOCK_SPECS.put("startActivity", "start_activity");
        BLOCK_SPECS.put("stringContains", "string_contains");
        BLOCK_SPECS.put("stringEquals", "string_equals");
        BLOCK_SPECS.put("stringIndex", "string_index");
        BLOCK_SPECS.put("stringJoin", "string_join");
        BLOCK_SPECS.put("stringLastIndex", "string_last_index");
        BLOCK_SPECS.put("stringLength", "string_length");
        BLOCK_SPECS.put("stringReplace", "string_replace");
        BLOCK_SPECS.put("stringReplaceAll", "string_replace_all");
        BLOCK_SPECS.put("stringReplaceFirst", "string_replace_first");
        BLOCK_SPECS.put("stringSub", "string_sub");
        BLOCK_SPECS.put("strToListMap", "str_to_list_map");
        BLOCK_SPECS.put("strToMap", "str_to_map");
        BLOCK_SPECS.put("textToSpeechIsSpeaking", "texttospeech_is_speaking");
        BLOCK_SPECS.put("textToSpeechSetPitch", "texttospeech_set_pitch");
        BLOCK_SPECS.put("textToSpeechSetSpeechRate", "texttospeech_set_speech_rate");
        BLOCK_SPECS.put("textToSpeechShutdown", "texttospeech_shutdown");
        BLOCK_SPECS.put("textToSpeechSpeak", "texttospeech_speak");
        BLOCK_SPECS.put("textToSpeechStop", "texttospeech_stop");
        BLOCK_SPECS.put("timerAfter", "timer_after");
        BLOCK_SPECS.put("timerCancel", "timer_cancel");
        BLOCK_SPECS.put("timerEvery", "timer_every");
        BLOCK_SPECS.put("toLowerCase", "to_lower_case");
        BLOCK_SPECS.put("toNumber", "to_number");
        BLOCK_SPECS.put("toString", "to_string");
        BLOCK_SPECS.put("toStringFormat", "to_string_format");
        BLOCK_SPECS.put("toStringWithDecimal", "to_string_with_decimal");
        BLOCK_SPECS.put("toUpperCase", "to_upper_case");
        BLOCK_SPECS.put("trim", "trim");
        BLOCK_SPECS.put("true", "true");
        BLOCK_SPECS.put("vibratorAction", "vibrator_action");
        BLOCK_SPECS.put("viewOnClick", "view_on_click");
        BLOCK_SPECS.put("webViewCanGoBack", "webview_can_go_back");
        BLOCK_SPECS.put("webViewCanGoForward", "webview_can_go_forward");
        BLOCK_SPECS.put("webViewClearCache", "webview_clear_cache");
        BLOCK_SPECS.put("webViewClearHistory", "webview_clear_history");
        BLOCK_SPECS.put("webViewGetUrl", "webview_get_url");
        BLOCK_SPECS.put("webViewGoBack", "webview_go_back");
        BLOCK_SPECS.put("webViewGoForward", "webview_go_forward");
        BLOCK_SPECS.put("webViewLoadUrl", "webview_load_url");
        BLOCK_SPECS.put("webViewSetCacheMode", "webview_set_cache_mode");
        BLOCK_SPECS.put("webViewStopLoading", "webview_stop_loading");
        BLOCK_SPECS.put("webViewZoomIn", "webview_zoom_in");
        BLOCK_SPECS.put("webViewZoomOut", "webview_zoom_out");
    }

    private static void initEventMenus() {
        EVENT_MENUS.put("initializeLogic", new String[]{});
        EVENT_MENUS.put("onAdClosed", new String[]{});
        EVENT_MENUS.put("onAdFailedToLoad", new String[]{"%d.errorCode"});
        EVENT_MENUS.put("onAdLoaded", new String[]{});
        EVENT_MENUS.put("onAdOpened", new String[]{});
        EVENT_MENUS.put("onAnimationCancel", new String[]{});
        EVENT_MENUS.put("onAnimationEnd", new String[]{});
        EVENT_MENUS.put("onAnimationStart", new String[]{});
        EVENT_MENUS.put("onBackPressed", new String[]{});
        EVENT_MENUS.put("onBindCustomView", new String[]{"%m.listMap.data", "%d.position"});
        EVENT_MENUS.put("onCancelled", new String[]{"%d.errorCode", "%s.errorMessage"});
        EVENT_MENUS.put("onCheckedChange", new String[]{"%b.isChecked"});
        EVENT_MENUS.put("onChildAdded", new String[]{"%s.childKey", "%m.varMap.childValue"});
        EVENT_MENUS.put("onChildChanged", new String[]{"%s.childKey", "%m.varMap.childValue"});
        EVENT_MENUS.put("onChildRemoved", new String[]{"%s.childKey", "%m.varMap.childValue"});
        EVENT_MENUS.put("onClick", new String[]{});
        EVENT_MENUS.put("onConnected", new String[]{"%s.tag", "%m.varMap.deviceData"});
        EVENT_MENUS.put("onConnectionError", new String[]{"%s.tag", "%s.connectionState", "%s.errorMessage"});
        EVENT_MENUS.put("onConnectionStopped", new String[]{"%s.tag"});
        EVENT_MENUS.put("onCreateUserComplete", new String[]{"%b.success", "%s.errorMessage"});
        EVENT_MENUS.put("onDataReceived", new String[]{"%s.tag", "%s.data"});
        EVENT_MENUS.put("onDataSent", new String[]{"%s.tag", "%s.data"});
        EVENT_MENUS.put("onDateChange", new String[]{"%d.year", "%d.month", "%d.day"});
        EVENT_MENUS.put("onDeleteSuccess", new String[]{});
        EVENT_MENUS.put("onDestroy", new String[]{});
        EVENT_MENUS.put("onDownloadProgress", new String[]{"%d.progressValue"});
        EVENT_MENUS.put("onDownloadSuccess", new String[]{"%d.totalByteCount"});
        EVENT_MENUS.put("onErrorResponse", new String[]{"%s.tag", "%s.message"});
        EVENT_MENUS.put("onFailure", new String[]{"%s.message"});
        EVENT_MENUS.put("onFilesPicked", new String[]{"%m.listStr.filePath"});
        EVENT_MENUS.put("onFilesPickedCancel", new String[]{});
        EVENT_MENUS.put("onItemClicked", new String[]{"%d.position"});
        EVENT_MENUS.put("onItemLongClicked", new String[]{"%d.position"});
        EVENT_MENUS.put("onItemSelected", new String[]{"%d.position"});
        EVENT_MENUS.put("onLocationChanged", new String[]{"%d.lat", "%d.lng", "%d.acc"});
        EVENT_MENUS.put("onMapReady", new String[]{});
        EVENT_MENUS.put("onMarkerClicked", new String[]{"%s.id"});
        EVENT_MENUS.put("onPageFinished", new String[]{"%s.url"});
        EVENT_MENUS.put("onPageStarted", new String[]{"%s.url"});
        EVENT_MENUS.put("onPause", new String[]{});
        EVENT_MENUS.put("onPictureTaken", new String[]{"%s.filePath"});
        EVENT_MENUS.put("onPictureTakenCancel", new String[]{});
        EVENT_MENUS.put("onPostCreate", new String[]{});
        EVENT_MENUS.put("onProgressChanged", new String[]{"%d.progressValue"});
        EVENT_MENUS.put("onResetPasswordEmailSent", new String[]{"%b.success"});
        EVENT_MENUS.put("onResume", new String[]{});
        EVENT_MENUS.put("onResponse", new String[]{"%s.tag", "%s.response", "%m.varMap.responseHeaders"});
        EVENT_MENUS.put("onSensorChanged", new String[]{"%d.x", "%d.y", "%d.z"});
        EVENT_MENUS.put("onSignInUserComplete", new String[]{"%b.success", "%s.errorMessage"});
        EVENT_MENUS.put("onSpeechError", new String[]{"%s.errorMessage"});
        EVENT_MENUS.put("onSpeechResult", new String[]{"%s.result"});
        EVENT_MENUS.put("onStart", new String[]{});
        EVENT_MENUS.put("onStartTrackingTouch", new String[]{});
        EVENT_MENUS.put("onStop", new String[]{});
        EVENT_MENUS.put("onStopTrackingTouch", new String[]{});
        EVENT_MENUS.put("onTextChanged", new String[]{"%s.charSeq"});
        EVENT_MENUS.put("onUploadProgress", new String[]{"%d.progressValue"});
        EVENT_MENUS.put("onUploadSuccess", new String[]{"%s.downloadUrl"});
    }

    private static void initEventSpecs() {
        EVENT_SPECS.put("initializeLogic", "initialize");
        EVENT_SPECS.put("onAdClosed", "on_ad_closed");
        EVENT_SPECS.put("onAdFailedToLoad", "on_ad_failed_to_load");
        EVENT_SPECS.put("onAdLoaded", "on_ad_loaded");
        EVENT_SPECS.put("onAdOpened", "on_ad_opened");
        EVENT_SPECS.put("onAnimationCancel", "on_animation_cancel");
        EVENT_SPECS.put("onAnimationEnd", "on_animation_end");
        EVENT_SPECS.put("onAnimationStart", "on_animation_start");
        EVENT_SPECS.put("onBackPressed", "on_back_pressed");
        EVENT_SPECS.put("onBindCustomView", "on_bind_custom_view");
        EVENT_SPECS.put("onCancelled", "on_cancelled");
        EVENT_SPECS.put("onCheckedChange", "on_check_changed");
        EVENT_SPECS.put("onChildAdded", "on_child_added");
        EVENT_SPECS.put("onChildChanged", "on_child_changed");
        EVENT_SPECS.put("onChildRemoved", "on_child_removed");
        EVENT_SPECS.put("onClick", "on_clicked");
        EVENT_SPECS.put("onConnected", "on_connected");
        EVENT_SPECS.put("onConnectionError", "on_connection_error");
        EVENT_SPECS.put("onConnectionStopped", "on_connection_stopped");
        EVENT_SPECS.put("onCreateUserComplete", "on_create_user_complete");
        EVENT_SPECS.put("onDataReceived", "on_data_received");
        EVENT_SPECS.put("onDataSent", "on_data_sent");
        EVENT_SPECS.put("onDateChange", "on_date_change");
        EVENT_SPECS.put("onDeleteSuccess", "on_delete_success");
        EVENT_SPECS.put("onDestroy", "on_destroy");
        EVENT_SPECS.put("onDownloadProgress", "on_download_progress");
        EVENT_SPECS.put("onDownloadSuccess", "on_download_success");
        EVENT_SPECS.put("onErrorResponse", "on_error_response");
        EVENT_SPECS.put("onFailure", "on_failure");
        EVENT_SPECS.put("onFilesPicked", "on_files_picked");
        EVENT_SPECS.put("onFilesPickedCancel", "on_files_picked_cancel");
        EVENT_SPECS.put("onItemClicked", "on_item_clicked");
        EVENT_SPECS.put("onItemLongClicked", "on_item_long_clicked");
        EVENT_SPECS.put("onItemSelected", "on_item_selected");
        EVENT_SPECS.put("onLocationChanged", "on_location_changed");
        EVENT_SPECS.put("onMapReady", "on_map_ready");
        EVENT_SPECS.put("onMarkerClicked", "on_marker_clicked");
        EVENT_SPECS.put("onPageFinished", "on_page_finished");
        EVENT_SPECS.put("onPageStarted", "on_page_started");
        EVENT_SPECS.put("onPause", "on_pause");
        EVENT_SPECS.put("onPictureTaken", "on_picture_taken");
        EVENT_SPECS.put("onPictureTakenCancel", "on_picture_taken_cancel");
        EVENT_SPECS.put("onPostCreate", "on_post_created");
        EVENT_SPECS.put("onProgressChanged", "on_progress_changed");
        EVENT_SPECS.put("onResetPasswordEmailSent", "on_reset_password_email_sent");
        EVENT_SPECS.put("onResponse", "on_response");
        EVENT_SPECS.put("onResume", "on_resume");
        EVENT_SPECS.put("onSensorChanged", "on_sensor_changed");
        EVENT_SPECS.put("onSignInUserComplete", "on_sign_in_user_complete");
        EVENT_SPECS.put("onSpeechError", "on_speech_error");
        EVENT_SPECS.put("onSpeechResult", "on_speech_result");
        EVENT_SPECS.put("onStart", "on_start");
        EVENT_SPECS.put("onStartTrackingTouch", "on_start_tracking_touch");
        EVENT_SPECS.put("onStop", "on_stop");
        EVENT_SPECS.put("onStopTrackingTouch", "on_stop_tracking_touch");
        EVENT_SPECS.put("onTextChanged", "on_text_changed");
        EVENT_SPECS.put("onUploadProgress", "on_upload_progress");
        EVENT_SPECS.put("onUploadSuccess", "on_upload_success");
    }

    // Note: The old decompiled code returned null for unknown blockNames.
    // This refactored version returns an empty list instead, which is safer
    // and avoids potential NPE in callers (e.g. StringResource.getBlockTranslation).
    public static ArrayList<String> getBlockParams(String blockName) {
        String[] params = BLOCK_PARAMS.get(blockName);
        if (params == null) return new ArrayList<>();
        ArrayList<String> list = new ArrayList<>(params.length);
        Collections.addAll(list, params);
        return list;
    }

    public static ArrayList<String> getBlockMenuItems(String blockName) {
        String[] items = EVENT_MENUS.get(blockName);
        if (items == null) return new ArrayList<>();
        ArrayList<String> list = new ArrayList<>(items.length);
        Collections.addAll(list, items);
        return list;
    }

    public static String getEventSpec(String blockName) {
        return EVENT_SPECS.getOrDefault(blockName, "initialize");
    }

    public static String getBlockSpec(String blockName) {
        return BLOCK_SPECS.getOrDefault(blockName, blockName);
    }
}
