package pro.sketchware.core;

import static com.besome.sketch.Config.VAR_DEFAULT_MIN_SDK_VERSION;
import static com.besome.sketch.Config.VAR_DEFAULT_TARGET_SDK_VERSION;
import static dev.aldi.sayuti.block.ExtraBlockFile.getExtraBlockData;

import static mod.hey.studios.util.ProjectFile.getDefaultColor;

import android.content.Context;
import android.content.pm.PackageInfo;
import android.content.pm.PackageManager;
import android.util.Log;

import java.io.FileInputStream;
import java.util.zip.CRC32;

import com.besome.sketch.beans.BlockBean;
import com.besome.sketch.beans.ComponentBean;
import com.besome.sketch.beans.ProjectFileBean;
import com.besome.sketch.beans.ProjectLibraryBean;
import com.besome.sketch.beans.SrcCodeBean;
import com.besome.sketch.beans.ViewBean;
import com.besome.sketch.editor.manage.library.material3.Material3LibraryManager;
import java.io.File;
import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.concurrent.ExecutionException;
import java.util.concurrent.ExecutorService;
import java.util.concurrent.Executors;
import java.util.concurrent.Future;
import java.util.regex.Pattern;

import android.util.Pair;

import dev.aldi.sayuti.block.ExtraBlockFile;
import mod.hey.studios.editor.manage.block.v2.BlockLoader;
import mod.hilal.saif.events.EventsHandler;
import mod.agus.jcoderz.editor.manage.library.locallibrary.ManageLocalLibrary;
import mod.hey.studios.build.BuildSettings;
import mod.hey.studios.project.ProjectSettings;
import mod.hey.studios.util.ProjectFile;
import mod.hilal.saif.android_manifest.AndroidManifestInjector;
import mod.hilal.saif.blocks.CommandBlock;
import mod.pranav.viewbinding.ViewBindingBuilder;
import pro.sketchware.SketchApplication;
import pro.sketchware.util.library.BuiltInLibraryManager;
import pro.sketchware.utility.FileUtil;
import pro.sketchware.xml.XmlBuilder;
import pro.sketchware.xml.XmlBuilderHelper;

public class ProjectFilePaths {

    /**
     * Firebase Database storage location RegExp matcher to remove unwanted parts of storage URL
     * to get the actual project ID.
     * <p/>
     * Users should enter the entire storage URL without <code>https://</code> at the beginning and
     * <code>/</code> at the end, e.g. <code>sk-pro-default-rtdb.firebaseio.com</code>.
     */
    private static final String FIREBASE_DATABASE_STORAGE_LOCATION_MATCHER = "(-default-rtdb)?\\.[a-z](.?)+";
    private static final Pattern PACKAGE_PLACEHOLDER_PATTERN = Pattern.compile("<\\?package_name\\?>");

    /**
     * Example content: /storage/emulated/0/.sketchware/mysc/605/app/src/main/assets
     */
    public final String assetsPath;

    /**
     * Example content: /storage/emulated/0/.sketchware/mysc/605/app/src/main/assets/fonts
     */
    public final String fontsPath;

    /**
     * Path of ZIP file containing compiled resources of the current project,
     * e.g. /storage/emulated/0/.sketchware/mysc/605/bin/InternalDemo.apk.res
     */
    public final String resourcesApkPath;

    /**
     * Example content: /storage/emulated/0/.sketchware/mysc/605/bin/classes.dex
     */
    public final String classesDexPath;

    /**
     * Example content: /storage/emulated/0/.sketchware/mysc/605/bin/InternalDemo.apk.unsigned
     */
    public final String unsignedUnalignedApkPath;

    /**
     * Example content: /storage/emulated/0/.sketchware/mysc/605/bin/InternalDemo.apk
     */
    public final String finalToInstallApkPath;

    /**
     * Example content: /storage/emulated/0/sketchware/signed_apk/InternalDemo_release.apk
     */
    public final String releaseApkPath;
    /**
     * Example content: /storage/emulated/0/.sketchware/mysc/605/bin/InternalDemo.apk.unsigned.aligned
     */
    public final String unsignedAlignedApkPath;
    public final String sc_id;
    /**
     * Example content: /storage/emulated/0/.sketchware/mysc/605/
     */
    public final String projectMyscPath;
    public final String projectName;
    public final String packageName;
    public final String applicationName;
    public final int colorAccent;
    public final int colorPrimary;
    public final int colorPrimaryDark;
    public final int colorControlHighlight;
    public final int colorControlNormal;
    public final String versionCode;
    public final String versionName;
    /**
     * Package name of current project,
     * but "folders" separated with slashes (/) instead of periods (.),
     * e.g. com/jbk/internal/demo
     */
    public final String packageNameAsFolders;
    /**
     * Path of file with ProGuard rules automatically generated by aapt2,
     * e.g. /storage/emulated/0/.sketchware/mysc/605/bin/aapt_rules.pro
     */
    public final String proguardAaptRules;
    /**
     * Path of ProGuard rules auto-generated to exclude built-in libraries and non-Full Mode Local libraries,
     * e.g. /storage/emulated/0/.sketchware/mysc/605/bin/rules_generated.pro
     */
    public final String proguardAutoGeneratedExclusions;
    /**
     * ProGuarded classes.jar file's path of current project,
     * e.g. /storage/emulated/0/.sketchware/mysc/605/bin/classes_proguard.jar
     */
    public final String proguardClassesPath;
    /**
     * Path of file containing the ProGuard mapping,
     * e.g. /storage/emulated/0/.sketchware/mysc/605/bin/mapping.txt
     */
    public final String proguardMappingPath;
    /**
     * Path of file containing ProGuard seeds,
     * e.g. /storage/emulated/0/.sketchware/mysc/605/bin/seeds.txt
     */
    public final String proguardSeedsPath;
    /**
     * Path of file containing ProGuard usage,
     * e.g. /storage/emulated/0/.sketchware/mysc/605/bin/usage.txt
     */
    public final String proguardUsagePath;
    /**
     * Current project's ProjectSettings object
     */
    public final ProjectSettings projectSettings;
    /**
     * Example content: /storage/emulated/0/.sketchware/mysc/605/app/src/main/AndroidManifest.xml
     */
    public final String androidManifestPath;
    /**
     * Example content: /storage/emulated/0/.sketchware/mysc/605/app/src/main
     */
    public final String generatedFilesPath;
    /**
     * Example content: /storage/emulated/0/.sketchware/mysc/605/bin
     */
    public final String binDirectoryPath;
    /**
     * Example content: /storage/emulated/0/.sketchware/mysc/605/bin/classes
     */
    public final String compiledClassesPath;
    /**
     * Project's generated R.java files directory,
     * e.g. /storage/emulated/0/.sketchware/mysc/605/gen
     */
    public final String rJavaDirectoryPath;
    /**
     * Example content: /storage/emulated/0/.sketchware/mysc/605/app/src/main/res
     */
    public final String resDirectoryPath;
    /**
     * Example content: /storage/emulated/0/.sketchware/mysc/605/app/src/main/proguard-rules.pro
     */
    public final String proguardFilePath;
    /**
     * Example content: /storage/emulated/0/.sketchware/mysc/605/app/src/main/res/layout
     */
    public final String layoutFilesPath;
    /**
     * Example content: /storage/emulated/0/.sketchware/mysc/605/app/src/main/java
     */
    public final String javaFilesPath;
    /**
     * Example content: /storage/emulated/0/.sketchware/mysc/605/app/src/main/res/raw
     */
    public final String importedSoundsPath;
    public final HashMap<String, Object> metadata;
    private final Material3LibraryManager material3LibraryManager;
    private final EncryptedFileUtil fileUtil;
    private final Context context;
    public BuildConfig buildConfig;
    public boolean generateDataBindingClasses;
    public boolean isAndroidStudioExport;
    private ExportType exportingType;

    public ProjectFilePaths(Context context, String sc_id) {
        this(context, SketchwarePaths.getMyscPath(sc_id), ProjectListManager.getProjectById(sc_id));
    }

    public ProjectFilePaths(Context context, String myscFolderPath, HashMap<String, Object> metadata) {
        this.context = context;
        this.metadata = metadata;
        buildConfig = new BuildConfig();
        sc_id = MapValueHelper.getString(metadata, "sc_id");
        material3LibraryManager = new Material3LibraryManager(sc_id);
        buildConfig.sc_id = sc_id;
        projectMyscPath = myscFolderPath.endsWith(File.separator) ? myscFolderPath : myscFolderPath + File.separator;
        packageName = MapValueHelper.getString(metadata, "my_sc_pkg_name");
        projectName = MapValueHelper.getString(metadata, "my_ws_name");
        applicationName = MapValueHelper.getString(metadata, "my_app_name");
        versionCode = MapValueHelper.getString(metadata, "sc_ver_code");
        versionName = MapValueHelper.getString(metadata, "sc_ver_name");

        colorAccent = MapValueHelper.get(metadata, ProjectFile.COLOR_ACCENT, getDefaultColor(ProjectFile.COLOR_ACCENT));
        colorPrimary = MapValueHelper.get(metadata, ProjectFile.COLOR_PRIMARY, getDefaultColor(ProjectFile.COLOR_PRIMARY));
        colorPrimaryDark = MapValueHelper.get(metadata, ProjectFile.COLOR_PRIMARY_DARK, getDefaultColor(ProjectFile.COLOR_PRIMARY_DARK));
        colorControlHighlight = MapValueHelper.get(metadata, ProjectFile.COLOR_CONTROL_HIGHLIGHT, getDefaultColor(ProjectFile.COLOR_CONTROL_HIGHLIGHT));
        colorControlNormal = MapValueHelper.get(metadata, ProjectFile.COLOR_CONTROL_NORMAL, getDefaultColor(ProjectFile.COLOR_CONTROL_NORMAL));

        projectSettings = new ProjectSettings(sc_id);
        fileUtil = new EncryptedFileUtil(true);
        packageNameAsFolders = packageName.replace(".", File.separator);
        binDirectoryPath = projectMyscPath + "bin";
        compiledClassesPath = binDirectoryPath + File.separator + "classes";
        proguardClassesPath = binDirectoryPath + File.separator + "classes_proguard.jar";
        proguardAaptRules = binDirectoryPath + File.separator + "aapt_rules.pro";
        proguardSeedsPath = binDirectoryPath + File.separator + "seeds.txt";
        proguardUsagePath = binDirectoryPath + File.separator + "usage.txt";
        proguardMappingPath = binDirectoryPath + File.separator + "mapping.txt";
        proguardAutoGeneratedExclusions = binDirectoryPath + File.separator + "rules_generated.pro";
        rJavaDirectoryPath = projectMyscPath + "gen";
        generatedFilesPath = projectMyscPath + "app" + File.separator + "src" + File.separator + "main";
        javaFilesPath = generatedFilesPath + File.separator + "java";
        resDirectoryPath = generatedFilesPath + File.separator + "res";
        proguardFilePath = projectMyscPath + "app" + File.separator + "proguard-rules.pro";
        layoutFilesPath = resDirectoryPath + File.separator + "layout";
        importedSoundsPath = resDirectoryPath + File.separator + "raw";
        assetsPath = generatedFilesPath + File.separator + "assets";
        fontsPath = assetsPath + File.separator + "fonts";
        androidManifestPath = projectMyscPath + "app" + File.separator + "src" + File.separator + "main" + File.separator + "AndroidManifest.xml";
        resourcesApkPath = binDirectoryPath + File.separator + projectName + ".apk.res";
        classesDexPath = binDirectoryPath + File.separator + "classes.dex";
        unsignedUnalignedApkPath = binDirectoryPath + File.separator + projectName + ".apk.unsigned";
        unsignedAlignedApkPath = unsignedUnalignedApkPath + ".aligned";
        finalToInstallApkPath = binDirectoryPath + File.separator + projectName + ".apk";
        releaseApkPath = SketchwarePaths.getSignedApkPath() + File.separator + projectName + "_release.apk";
    }

    /**
     * Deletes the directory {@link ProjectFilePaths#resDirectoryPath}/values-v21/.
     */
    public void deleteValuesV21Directory() {
        File file = new File(resDirectoryPath + File.separator + "values-v21");
        if (file.exists()) {
            fileUtil.deleteDirectory(file);
        }
    }

    /**
     * Creates needed build directories {@link ProjectFilePaths#binDirectoryPath}, {@link ProjectFilePaths#compiledClassesPath}, {@link ProjectFilePaths#rJavaDirectoryPath}, {@link ProjectFilePaths#javaFilesPath}, {@link ProjectFilePaths#resDirectoryPath},
     * {@link ProjectFilePaths#layoutFilesPath}, {@link ProjectFilePaths#importedSoundsPath}, {@link ProjectFilePaths#assetsPath}, and {@link ProjectFilePaths#fontsPath}.
     */
    public void createBuildDirectories(Context context) {
        fileUtil.mkdirs(binDirectoryPath);
        fileUtil.mkdirs(compiledClassesPath);
        fileUtil.mkdirs(rJavaDirectoryPath);
        fileUtil.mkdirs(javaFilesPath);
        fileUtil.mkdirs(resDirectoryPath);
        fileUtil.mkdirs(layoutFilesPath);
        fileUtil.mkdirs(importedSoundsPath);
        fileUtil.mkdirs(assetsPath);
        fileUtil.mkdirs(fontsPath);
    }

    /**
     * Prepares to compile and creates /Internal storage/.sketchware/mysc/&lt;sc_id&gt;/ directories,
     * {@link ProjectFilePaths#binDirectoryPath}, {@link ProjectFilePaths#compiledClassesPath} and {@link ProjectFilePaths#rJavaDirectoryPath}.
     */
    public void prepareBuildDirectories() {
        fileUtil.mkdirs(binDirectoryPath);
        fileUtil.mkdirs(compiledClassesPath);
        fileUtil.mkdirs(rJavaDirectoryPath);
    }

    /**
     * Deletes temporary compile cache directories, {@link ProjectFilePaths#binDirectoryPath} and {@link ProjectFilePaths#rJavaDirectoryPath}. The used method
     * logs all files and folders which get deleted.
     */
    public void cleanBuildCache() {
        fileUtil.deleteDirectoryByPath(binDirectoryPath);
        fileUtil.deleteDirectoryByPath(rJavaDirectoryPath);
    }

    /**
     * Incremental-build variant of {@link #cleanBuildCache()}: only deletes the R.java
     * directory so that AAPT2 can regenerate a fresh R.java, while leaving the compiled
     * {@code .class} files intact for reuse by the incremental ECJ compile step.
     */
    public void cleanRJavaOnly() {
        fileUtil.deleteDirectoryByPath(rJavaDirectoryPath);
    }

    /**
     * Generates top-level build.gradle, build.gradle for module ':app' and settings.gradle files.
     */
    public void generateGradleFiles() {
        fileUtil.writeText(projectMyscPath + File.separator + "app" + File.separator + "build.gradle",
                ComponentCodeGenerator.getBuildGradleString(VAR_DEFAULT_TARGET_SDK_VERSION, VAR_DEFAULT_MIN_SDK_VERSION, projectSettings.getValue(ProjectSettings.SETTING_TARGET_SDK_VERSION, String.valueOf(VAR_DEFAULT_TARGET_SDK_VERSION)), buildConfig, projectSettings.getValue(ProjectSettings.SETTING_ENABLE_VIEWBINDING, ProjectSettings.SETTING_GENERIC_VALUE_FALSE).equals(ProjectSettings.SETTING_GENERIC_VALUE_TRUE)));
        fileUtil.writeText(projectMyscPath + File.separator + "settings.gradle", ComponentCodeGenerator.getSettingsGradle());
        fileUtil.writeText(projectMyscPath + File.separator + "build.gradle", ComponentCodeGenerator.getTopLevelBuildGradle("8.12.0", "4.4.3"));

        fileUtil.writeText(projectMyscPath + File.separator + "gradle.properties", """
                android.enableR8.fullMode=false
                android.enableJetifier=true
                android.useAndroidX=true
                """.trim());
    }

    /**
     * Extracts a ZIP archive from assets to {@link ProjectFilePaths#resDirectoryPath}.
     */
    public void extractAssetsToRes(Context context, String assetZipName) {
        try {
            ZipUtil.extractAssetZip(context, assetZipName, resDirectoryPath);
        } catch (RuntimeException ex) {
            Log.e("ProjectFilePaths", ex.getMessage(), ex);
        }
    }

    /**
     * Copies a file to the project's app icon path, {@link ProjectFilePaths#resDirectoryPath}/drawable-xhdpi/app_icon.png
     */
    public void copyAppIcon(String iconPath) {
        try {
            fileUtil.copyFile(iconPath, resDirectoryPath + File.separator + "mipmap-xhdpi" + File.separator + "ic_launcher.png");
        } catch (IOException ex) {
            Log.e("ProjectFilePaths", ex.getMessage(), ex);
        }
    }

    /**
     * Copies a mipMaps folder to the project's app icon path, {@link ProjectFilePaths#resDirectoryPath}/mipmap
     */

    public void copyMipmapFolder(String iconPath) {
        try {
            FileUtil.copyDirectory(new File(iconPath), new File(resDirectoryPath + File.separator));
        } catch (IOException ex) {
            Log.e("ProjectFilePaths", ex.getMessage(), ex);
        }
    }

    /**
     * Creates ic_launcher.xml to the project's app icon path, {@link ProjectFilePaths#resDirectoryPath}/mipmap-anydpi-v26
     */

    public void createLauncherIconXml(String content) {
        String iconPath = resDirectoryPath + File.separator + "mipmap-anydpi-v26" + File.separator + "ic_launcher.xml";
        if (!fileUtil.writeText(iconPath, content)) {
            Log.e("ProjectFilePaths", "Failed to write launcher icon xml: " + iconPath);
        }
    }

    /**
     * Generates DebugActivity.java, SketchApplication.java, and SketchLogger.java, if necessary.
     */
    public void generateDebugFiles(Context context) {
        boolean logcatEnabled = buildConfig.isDebugBuild && new BuildSettings(sc_id).getValue(
                        BuildSettings.SETTING_ENABLE_LOGCAT, BuildSettings.SETTING_GENERIC_VALUE_TRUE)
                .equals(BuildSettings.SETTING_GENERIC_VALUE_TRUE);

        String javaDir = SketchwarePaths.getProjectJavaPath(sc_id) + File.separator;

        File debugActivityFile = new File(javaDir, "DebugActivity.java");
        if (!debugActivityFile.exists()) {
            String debugActivityContent = fileUtil.readAssetFile(
                    context,
                    "debug" + File.separator + "DebugActivity.java"
            );
            debugActivityContent = PACKAGE_PLACEHOLDER_PATTERN.matcher(debugActivityContent).replaceAll(packageName);
            fileUtil.writeText(javaFilesPath + File.separator + packageNameAsFolders + File.separator + "DebugActivity.java", debugActivityContent);
        }

        String customApplicationClassName = new ProjectSettings(sc_id).getValue(
                ProjectSettings.SETTING_APPLICATION_CLASS, ".SketchApplication");
        boolean notUsingCustomApplicationClass = customApplicationClassName.equals(".SketchApplication");

        if (!customApplicationClassName.startsWith(".")) {
            customApplicationClassName = "." + customApplicationClassName; // since sketchware don't allow creating any java file outside the package name
        }

        String fullCustomClassName = packageName + customApplicationClassName;

        int lastDot = fullCustomClassName.lastIndexOf('.');
        String customClassSimpleName = fullCustomClassName.substring(lastDot + 1);
        String customClassPackage = fullCustomClassName.substring(0, lastDot);
        String customClassPackageAsFolders = customClassPackage.replace('.', File.separatorChar);

        File targetApplicationFile = new File(javaDir + File.separator +
                customApplicationClassName.substring(1).replace('.', '/') + ".java");

        if (!targetApplicationFile.exists()) {
            boolean applyMultiDex = projectSettings.getMinSdkVersion() < 21;
            String sketchApplicationFileContent = fileUtil.readAssetFile(
                    context,
                    "debug" + File.separator + "SketchApplication.java"
            );
            sketchApplicationFileContent = PACKAGE_PLACEHOLDER_PATTERN.matcher(sketchApplicationFileContent).replaceAll(packageName);

            if (applyMultiDex) {
                sketchApplicationFileContent = sketchApplicationFileContent.replace(
                        "Application {", "androidx.multidex.MultiDexApplication {");
            }
            if (logcatEnabled) {
                sketchApplicationFileContent = sketchApplicationFileContent.replace(
                                "super.onCreate();", "SketchLogger.startLogging();\n        super.onCreate();")
                        .replace("Process.killProcess(Process.myPid());",
                                "SketchLogger.broadcastLog(Log.getStackTraceString(throwable));\n" +
                                        "                    Process.killProcess(Process.myPid());"
                        );
            }
            if (new Material3LibraryManager(sc_id).isDynamicColorsEnabled()) {
                sketchApplicationFileContent = sketchApplicationFileContent.replace(
                                "mApplicationContext = getApplicationContext();",
                                "mApplicationContext = getApplicationContext();\n        DynamicColors.applyToActivitiesIfAvailable(this);")
                        .replace("import android.util.Log;", "import android.util.Log;\nimport com.google.android.material.color.DynamicColors;");
            }
            if (!notUsingCustomApplicationClass) {
                sketchApplicationFileContent = sketchApplicationFileContent.replace(
                        "public class SketchApplication", "public class " + customClassSimpleName);
                sketchApplicationFileContent = sketchApplicationFileContent.replace(
                        "package " + packageName + ";", "package " + customClassPackage + ";");

                String imports = "import android.util.Log;\nimport " + packageName + ".DebugActivity;";
                if (logcatEnabled) {
                    imports += "\nimport " + packageName + ".SketchLogger;";
                }
                sketchApplicationFileContent = sketchApplicationFileContent.replace(
                        "import android.util.Log;", imports);
            }

            fileUtil.writeText(javaFilesPath + File.separator
                    + customClassPackageAsFolders + File.separator
                    + customClassSimpleName + ".java", sketchApplicationFileContent);
        }

        if (logcatEnabled) {
            File sketchLoggerFile = new File(javaDir, "SketchLogger.java");
            if (!sketchLoggerFile.exists()) {
                String sketchLoggerFileContent = fileUtil.readAssetFile(
                        context,
                        "debug" + File.separator + "SketchLogger.java"
                );

                sketchLoggerFileContent = PACKAGE_PLACEHOLDER_PATTERN.matcher(sketchLoggerFileContent).replaceAll(packageName);

                sketchLoggerFileContent = sketchLoggerFileContent.replace("<?class_name_package?>", customClassPackage);

                sketchLoggerFileContent = sketchLoggerFileContent.replace("<?class_name?>", customClassSimpleName);

                fileUtil.writeText(javaFilesPath + File.separator + packageNameAsFolders + File.separator + "SketchLogger.java",
                        sketchLoggerFileContent);
            }
        }
    }

    /**
     * Writes a project file to its correct location. Java files, for example, get saved to
     * <pre>
     *     {@link ProjectFilePaths#javaFilesPath} + File.separator + {@link ProjectFilePaths#packageNameAsFolders}
     * </pre>, while AndroidManifest.xml gets saved to {@link ProjectFilePaths#androidManifestPath}.
     */
    public void writeProjectFile(String fileName, String fileContent) {
        if (fileName.endsWith("java")) {
            fileUtil.writeText(javaFilesPath + File.separator + packageNameAsFolders + File.separator + fileName, fileContent);
        } else if (fileName.equals("AndroidManifest.xml")) {
            fileUtil.writeText(androidManifestPath, fileContent);
        } else if (fileName.equals("colors.xml") || fileName.equals("styles.xml") || fileName.equals("strings.xml")) {
            fileUtil.writeText(resDirectoryPath + File.separator + "values" + File.separator + fileName, fileContent);
        } else if (fileName.equals("provider_paths.xml")) {
            fileUtil.writeText(resDirectoryPath + File.separator + "xml" + File.separator + fileName, fileContent);
        } else {
            fileUtil.writeText(layoutFilesPath + File.separator + fileName, fileContent);
        }
    }

    /**
     * Initialize project metadata
     */
    public void initializeMetadata(LibraryManager projectLibraryManager, ProjectFileManager projectFileManager, ProjectDataStore projectDataManager) {
        initializeMetadata(projectLibraryManager, projectFileManager, projectDataManager, ExportType.DEBUG_APP);
    }

    public void initializeMetadata(LibraryManager projectLibraryManager, ProjectFileManager projectFileManager, ProjectDataStore projectDataManager, ExportType exportingType) {
        ProjectLibraryBean adMob = projectLibraryManager.getAdmob();
        ProjectLibraryBean appCompat = projectLibraryManager.getCompat();
        ProjectLibraryBean firebase = projectLibraryManager.getFirebaseDB();
        ProjectLibraryBean googleMaps = projectLibraryManager.getGoogleMap();
        this.exportingType = exportingType;
        buildConfig = new BuildConfig();
        buildConfig.packageName = packageName;
        buildConfig.projectName = applicationName;
        buildConfig.versionCode = versionCode;
        buildConfig.versionName = versionName;
        buildConfig.sc_id = sc_id;
        buildConfig.isDebugBuild = exportingType == ExportType.DEBUG_APP;
        isAndroidStudioExport = exportingType == ExportType.ANDROID_STUDIO;
        generateDataBindingClasses = !(exportingType == ExportType.DEBUG_APP || exportingType == ExportType.ANDROID_STUDIO);
        if (firebase.useYn.equals(ProjectLibraryBean.LIB_USE_Y)) {
            buildConfig.isFirebaseEnabled = true;
            buildConfig.addPermission(BuildConfig.PERMISSION_INTERNET);
            buildConfig.addPermission(BuildConfig.PERMISSION_ACCESS_NETWORK_STATE);
        }
        if (appCompat.useYn.equals(ProjectLibraryBean.LIB_USE_Y)) {
            buildConfig.isAppCompatEnabled = true;
        }
        if (adMob.useYn.equals(ProjectLibraryBean.LIB_USE_Y)) {
            buildConfig.isAdMobEnabled = true;
            buildConfig.addPermission(BuildConfig.PERMISSION_INTERNET);
            buildConfig.addPermission(BuildConfig.PERMISSION_ACCESS_NETWORK_STATE);
            buildConfig.setupAdmob(adMob);
        }
        if (googleMaps.useYn.equals(ProjectLibraryBean.LIB_USE_Y)) {
            buildConfig.isMapUsed = true;
            buildConfig.addPermission(BuildConfig.PERMISSION_INTERNET);
            buildConfig.addPermission(BuildConfig.PERMISSION_ACCESS_NETWORK_STATE);
            buildConfig.setupGoogleMap(googleMaps);
        }
        for (ProjectFileBean customView : projectFileManager.getCustomViews()) {
            for (ViewBean viewBean : ProjectDataStore.getSortedRootViews(projectDataManager.getViews(customView.getXmlName()))) {
                var classNameParts = viewBean.convert.split("\\.");
                var className = classNameParts[classNameParts.length - 1];
                switch (className) {
                    case "CircleImageView" -> buildConfig.constVarComponent.isCircleImageViewUsed = true;
                    case "CodeView" -> buildConfig.constVarComponent.isCodeViewUsed = true;
                    case "LottieAnimationView" -> buildConfig.constVarComponent.isLottieUsed = true;
                    case "OTPView" -> buildConfig.constVarComponent.isOTPViewUsed = true;
                    case "PatternLockView" -> buildConfig.constVarComponent.isPatternLockViewUsed = true;
                    case "WaveSideBar" -> buildConfig.constVarComponent.isWaveSideBarUsed = true;
                    case "YouTubePlayerView" -> buildConfig.constVarComponent.isYoutubePlayerUsed = true;
                    case "SwipeRefreshLayout" -> buildConfig.constVarComponent.isSwipeRefreshLayoutUsed = true;
                }
            }
        }
        for (ProjectFileBean activity : projectFileManager.getActivities()) {
            if (activity.hasActivityOption(ProjectFileBean.OPTION_ACTIVITY_DRAWER)) {
                buildConfig.getActivityPermissions(activity.getActivityName()).hasDrawer = true;
            }
            for (ComponentBean component : projectDataManager.getComponents(activity.getJavaName())) {
                switch (component.type) {
                    case ComponentBean.COMPONENT_TYPE_CAMERA, ComponentBean.COMPONENT_TYPE_CAMERA_LEGACY -> {
                        buildConfig.isAppCompatEnabled = true;
                        buildConfig.isFileProviderUsed = true;
                        buildConfig.addPermission(activity.getActivityName(), BuildConfig.PERMISSION_CAMERA);
                        buildConfig.addPermission(activity.getActivityName(), BuildConfig.PERMISSION_READ_EXTERNAL_STORAGE);
                        buildConfig.addPermission(activity.getActivityName(), BuildConfig.PERMISSION_WRITE_EXTERNAL_STORAGE);
                    }
                    case ComponentBean.COMPONENT_TYPE_FILE_PICKER ->
                            buildConfig.addPermission(activity.getActivityName(), BuildConfig.PERMISSION_READ_EXTERNAL_STORAGE);
                    case ComponentBean.COMPONENT_TYPE_FIREBASE -> {
                        buildConfig.isGsonUsed = true;
                        buildConfig.isFirebaseDatabaseUsed = true;
                        buildConfig.addPermission(activity.getActivityName(), BuildConfig.PERMISSION_INTERNET);
                        buildConfig.addPermission(activity.getActivityName(), BuildConfig.PERMISSION_ACCESS_NETWORK_STATE);
                    }
                    case ComponentBean.COMPONENT_TYPE_FIREBASE_STORAGE -> {
                        buildConfig.isFirebaseStorageUsed = true;
                        buildConfig.addPermission(activity.getActivityName(), BuildConfig.PERMISSION_READ_EXTERNAL_STORAGE);
                        buildConfig.addPermission(activity.getActivityName(), BuildConfig.PERMISSION_WRITE_EXTERNAL_STORAGE);
                    }
                    case ComponentBean.COMPONENT_TYPE_VIBRATOR ->
                            buildConfig.addPermission(activity.getActivityName(), BuildConfig.PERMISSION_VIBRATE);
                    case ComponentBean.COMPONENT_TYPE_FIREBASE_AUTH -> {
                        buildConfig.isFirebaseAuthUsed = true;
                        buildConfig.getActivityPermissions(activity.getActivityName()).usesFirebaseAuth = true;
                    }
                    case ComponentBean.COMPONENT_TYPE_FIREBASE_AUTH_PHONE -> {
                        buildConfig.isFirebaseAuthUsed = true;
                        buildConfig.getActivityPermissions(activity.getActivityName()).usesFirebaseAuth = true;
                    }
                    case ComponentBean.COMPONENT_TYPE_REQUEST_NETWORK -> {
                        buildConfig.isGsonUsed = true;
                        buildConfig.isHttp3Used = true;
                        buildConfig.addPermission(activity.getActivityName(), BuildConfig.PERMISSION_INTERNET);
                        buildConfig.addPermission(activity.getActivityName(), BuildConfig.PERMISSION_ACCESS_NETWORK_STATE);
                    }
                    case ComponentBean.COMPONENT_TYPE_TEXT_TO_SPEECH -> buildConfig.isTextToSpeechUsed = true;
                    case ComponentBean.COMPONENT_TYPE_SPEECH_TO_TEXT -> {
                        buildConfig.isSpeechToTextUsed = true;
                        buildConfig.addPermission(activity.getActivityName(), BuildConfig.PERMISSION_RECORD_AUDIO);
                    }
                    case ComponentBean.COMPONENT_TYPE_BLUETOOTH_CONNECT -> {
                        buildConfig.addPermission(activity.getActivityName(), BuildConfig.PERMISSION_BLUETOOTH);
                        buildConfig.addPermission(activity.getActivityName(), BuildConfig.PERMISSION_BLUETOOTH_ADMIN);
                        buildConfig.addPermission(activity.getActivityName(), BuildConfig.PERMISSION_BLUETOOTH_CONNECT);
                    }
                    case ComponentBean.COMPONENT_TYPE_LOCATION_MANAGER ->
                            buildConfig.addPermission(activity.getActivityName(), BuildConfig.PERMISSION_ACCESS_FINE_LOCATION);
                    case ComponentBean.COMPONENT_TYPE_NOTIFICATION ->
                            buildConfig.isNotificationUsed = true;
                    case ComponentBean.COMPONENT_TYPE_FIREBASE_CLOUD_MESSAGE ->
                            buildConfig.constVarComponent.isFCMUsed = true;
                    case ComponentBean.COMPONENT_TYPE_FIREBASE_AUTH_GOOGLE_LOGIN ->
                            buildConfig.constVarComponent.isFBGoogleUsed = true;
                    default -> {
                    }
                }
            }

            for (ViewBean view : ProjectDataStore.getSortedRootViews(projectDataManager.getViews(activity.getXmlName()))) {
                var classNameParts = view.convert.split("\\.");
                var className = classNameParts[classNameParts.length - 1];
                switch (className) {
                    case "CircleImageView" -> buildConfig.constVarComponent.isCircleImageViewUsed = true;
                    case "CodeView" -> buildConfig.constVarComponent.isCodeViewUsed = true;
                    case "LottieAnimationView" -> buildConfig.constVarComponent.isLottieUsed = true;
                    case "OTPView" -> buildConfig.constVarComponent.isOTPViewUsed = true;
                    case "PatternLockView" -> buildConfig.constVarComponent.isPatternLockViewUsed = true;
                    case "WaveSideBar" -> buildConfig.constVarComponent.isWaveSideBarUsed = true;
                    case "YouTubePlayerView" -> buildConfig.constVarComponent.isYoutubePlayerUsed = true;
                    case "SwipeRefreshLayout" -> buildConfig.constVarComponent.isSwipeRefreshLayoutUsed = true;
                }
            }

            for (Map.Entry<String, ArrayList<BlockBean>> entry : projectDataManager.getBlockMap(activity.getJavaName()).entrySet()) {
                for (BlockBean block : entry.getValue()) {
                    switch (block.opCode) {
                        case "intentSetAction":
                            // If an Intent setAction (ACTION_CALL) block is used
                            if (block.parameters.get(1).equals(BlockConstants.INTENT_ACTIONS[1])) {
                                buildConfig.addPermission(activity.getActivityName(), BuildConfig.PERMISSION_CALL_PHONE);
                            }
                            break;

                        case "fileutilread":
                        case "fileutilisexist":
                        case "fileutillistdir":
                        case "fileutilisdir":
                        case "fileutilisfile":
                        case "fileutillength":
                        case "fileutilStartsWith":
                        case "fileutilEndsWith":
                        case "getJpegRotate":
                        case "setImageFilePath":
                        case "fileutilGetLastSegmentPath":
                            buildConfig.addPermission(activity.getActivityName(), BuildConfig.PERMISSION_READ_EXTERNAL_STORAGE);
                            break;

                        case "fileutilwrite":
                        case "fileutilcopy":
                        case "fileutilcopydir":
                        case "fileutilmove":
                        case "fileutildelete":
                        case "fileutilmakedir":
                        case "resizeBitmapFileRetainRatio":
                        case "resizeBitmapFileToSquare":
                        case "resizeBitmapFileToCircle":
                        case "resizeBitmapFileWithRoundedBorder":
                        case "cropBitmapFileFromCenter":
                        case "rotateBitmapFile":
                        case "scaleBitmapFile":
                        case "skewBitmapFile":
                        case "setBitmapFileColorFilter":
                        case "setBitmapFileBrightness":
                        case "setBitmapFileContrast":
                            buildConfig.addPermission(activity.getActivityName(), BuildConfig.PERMISSION_READ_EXTERNAL_STORAGE);
                            buildConfig.addPermission(activity.getActivityName(), BuildConfig.PERMISSION_WRITE_EXTERNAL_STORAGE);
                            break;

                        case "strToMap":
                        case "mapToStr":
                        case "strToListMap":
                        case "listMapToStr":
                        case "GsonListTojsonString":
                        case "GsonStringToListString":
                        case "GsonStringToListNumber":
                            buildConfig.isGsonUsed = true;
                            break;

                        case "setImageUrl":
                            buildConfig.isGlideUsed = true;
                            buildConfig.addPermission(BuildConfig.PERMISSION_INTERNET);
                            break;

                        case "webViewLoadUrl":
                            buildConfig.addPermission(BuildConfig.PERMISSION_INTERNET);
                            buildConfig.addPermission(BuildConfig.PERMISSION_ACCESS_NETWORK_STATE);
                            break;

                        default:
                    }
                }
            }
            buildConfig.reset();
        }
    }

    public void generateProjectFiles(ProjectFileManager projectFileManager, ProjectDataStore projectDataManger, LibraryManager projectLibraryManager, BuiltInLibraryManager builtInLibraryManager) {
        long generateProjectFilesStarted = System.currentTimeMillis();
        long generateSourceCodeBeansStarted = System.currentTimeMillis();
        ArrayList<SrcCodeBean> srcCodeBeans = generateSourceCodeBeans(projectFileManager, projectDataManger, projectLibraryManager, builtInLibraryManager);
        long generateSourceCodeBeansDuration = System.currentTimeMillis() - generateSourceCodeBeansStarted;
        int javaBeanCount = 0;
        int xmlBeanCount = 0;
        int otherBeanCount = 0;
        for (SrcCodeBean bean : srcCodeBeans) {
            if (bean.srcFileName.endsWith(".java")) {
                javaBeanCount++;
            } else if (bean.srcFileName.endsWith(".xml")) {
                xmlBeanCount++;
            } else {
                otherBeanCount++;
            }
        }
        Log.d("ProjectFilePaths", "generateProjectFiles: generateSourceCodeBeans produced " + srcCodeBeans.size()
                + " bean(s) (java=" + javaBeanCount
                + ", xml=" + xmlBeanCount
                + ", other=" + otherBeanCount
                + ") in " + generateSourceCodeBeansDuration + " ms");
        int writtenProjectFileCount = 0;
        long writeProjectFilesStarted = System.currentTimeMillis();
        if (buildConfig.isFileProviderUsed) {
            XmlBuilder pathsTag = new XmlBuilder("paths");
            pathsTag.addAttribute("xmlns", "android", "http://schemas.android.com/apk/res/android");
            XmlBuilder externalPathTag = new XmlBuilder("external-path");
            externalPathTag.addAttribute("", "name", "files_path");
            externalPathTag.addAttribute("", "path", ".");
            pathsTag.addChildNode(externalPathTag);
            String filePath = "xml/file_paths.xml";
            writeProjectFile(filePath, pathsTag.toCode());
            writtenProjectFileCount++;
        }
        for (SrcCodeBean bean : srcCodeBeans) {
            writeProjectFile(bean.srcFileName, bean.source);
            writtenProjectFileCount++;
        }
        long writeProjectFilesDuration = System.currentTimeMillis() - writeProjectFilesStarted;
        boolean generatedSecrets = buildConfig.isFirebaseEnabled || buildConfig.isAdMobEnabled || buildConfig.isMapUsed;
        long generateSecretsStarted = System.currentTimeMillis();
        if (generatedSecrets) {
            CommandBlock.clearTempCommands();
            try {
                prepareXmlCommands(projectFileManager, projectDataManger);
                ProjectLibraryBean firebaseLibrary = projectLibraryManager.getFirebaseDB();
                XmlBuilderHelper xmlBuilder = new XmlBuilderHelper();
                xmlBuilder.addInteger("google_play_services_version", 12451000);
                if (buildConfig.isFirebaseEnabled) {
                    String databaseUrl;
                    String projectId;
                    String libraryData = firebaseLibrary.data;
                    if (libraryData.contains(".")) {
                        databaseUrl = "https://" + libraryData;
                        projectId = libraryData.trim().replaceAll(FIREBASE_DATABASE_STORAGE_LOCATION_MATCHER, "");
                    } else {
                        databaseUrl = "https://" + libraryData + ".firebaseio.com";
                        projectId = libraryData;
                    }
                    xmlBuilder.addString("firebase_database_url", databaseUrl, false);
                    xmlBuilder.addString("project_id", projectId, false);
                    xmlBuilder.addString("google_app_id", firebaseLibrary.reserved1, false);
                    if (firebaseLibrary.reserved2 != null && !firebaseLibrary.reserved2.isEmpty()) {
                        xmlBuilder.addString("google_api_key", firebaseLibrary.reserved2, false);
                    }
                    if (firebaseLibrary.reserved3 != null && !firebaseLibrary.reserved3.isEmpty()) {
                        xmlBuilder.addString("google_storage_bucket", firebaseLibrary.reserved3, false);
                    }
                }
                if (buildConfig.isMapUsed) {
                    xmlBuilder.addString("google_maps_key", projectLibraryManager.getGoogleMap().data, false);
                }
                String filePath = "values/secrets.xml";
                fileUtil.writeText(resDirectoryPath + File.separator + filePath,
                        CommandBlock.applyCommands(filePath, xmlBuilder.toCode()));
            } finally {
                CommandBlock.clearTempCommands();
            }
        }
        long generateSecretsDuration = System.currentTimeMillis() - generateSecretsStarted;
        long generateGradleFilesStarted = System.currentTimeMillis();
        generateGradleFiles();
        long generateGradleFilesDuration = System.currentTimeMillis() - generateGradleFilesStarted;
        Log.d("ProjectFilePaths", "generateProjectFiles: wrote " + writtenProjectFileCount
                + " generated file(s) in " + writeProjectFilesDuration + " ms"
                + ", generatedSecrets=" + generatedSecrets
                + " (" + generateSecretsDuration + " ms)"
                + ", generateGradleFiles=" + generateGradleFilesDuration + " ms"
                + ", total=" + (System.currentTimeMillis() - generateProjectFilesStarted) + " ms");
    }

    public ArrayList<SrcCodeBean> generateSourceCodeBeans(ProjectFileManager projectFileManager, ProjectDataStore projectDataManager, BuiltInLibraryManager builtInLibraryManager) {
        return generateSourceCodeBeans(projectFileManager, projectDataManager, ProjectDataManager.getLibraryManager(sc_id), builtInLibraryManager);
    }

    /**
     * Get source code files that are viewable in SrcCodeViewer
     */
    public ArrayList<SrcCodeBean> generateSourceCodeBeans(ProjectFileManager projectFileManager, ProjectDataStore projectDataManager, LibraryManager projectLibraryManager, BuiltInLibraryManager builtInLibraryManager) {
        long generateSourceCodeBeansStarted = System.currentTimeMillis();
        generateDebugFiles(SketchApplication.getAppContext());
        CommandBlock.clearTempCommands();
        try {
            String javaDir = SketchwarePaths.getProjectJavaPath(sc_id) + File.separator;
            String layoutDir = SketchwarePaths.getProjectLayoutPath(sc_id) + File.separator;
            List<File> javaFiles;
            {
                File[] files = new File(javaDir).listFiles();
                if (files == null) files = new File[0];
                javaFiles = Arrays.asList(files);
            }
            List<File> layoutFiles;
            {
                File[] files = new File(layoutDir).listFiles();
                if (files == null) files = new File[0];
                layoutFiles = Arrays.asList(files);
            }

            // Generate Activities unless a custom version of it exists already
            // at /Internal storage/.sketchware/data/<sc_id>/files/java/
            ArrayList<SrcCodeBean> srcCodeBeans = new ArrayList<>();

            List<ProjectFileBean> activitiesToGenerate = new ArrayList<>();
            for (ProjectFileBean activity : projectFileManager.getActivities()) {
                if (!javaFiles.contains(new File(javaDir + activity.getJavaName()))) {
                    activitiesToGenerate.add(activity);
                }
            }

            // Code generation cache: skip regeneration if inputs haven't changed
            File codegenCacheDir = new File(SketchApplication.getAppContext().getCacheDir(), "codegenCache/" + sc_id);
            String cacheKey = computeCodeGenCacheKey(projectFileManager, projectDataManager, projectLibraryManager);
            String cacheKeyHash = Integer.toHexString(cacheKey.hashCode());
            boolean cacheHit = false;
            String codegenCacheDecision = "cacheKeyFileMissing";
            int cachedActivitiesLoaded = 0;
            int missingCachedFiles = 0;
            long codegenCacheLookupStarted = System.currentTimeMillis();

            File cacheKeyFile = new File(codegenCacheDir, "cache.key");
            if (cacheKeyFile.exists()) {
                try {
                    String cachedKey = FileUtil.readFile(cacheKeyFile.getAbsolutePath());
                    if (cacheKey.equals(cachedKey)) {
                        // Try to load all activities from cache
                        boolean allCached = true;
                        ArrayList<SrcCodeBean> cachedBeans = new ArrayList<>();
                        for (ProjectFileBean activity : activitiesToGenerate) {
                            File cachedFile = new File(codegenCacheDir, activity.getJavaName() + ".code");
                            if (cachedFile.exists()) {
                                String cachedCode = FileUtil.readFile(cachedFile.getAbsolutePath());
                                cachedBeans.add(new SrcCodeBean(activity.getJavaName(),
                                        ActivityCodeGenerator.applyCommands(cachedCode)));
                            } else {
                                allCached = false;
                                missingCachedFiles = activitiesToGenerate.size() - cachedBeans.size();
                                break;
                            }
                        }
                        if (allCached) {
                            srcCodeBeans.addAll(cachedBeans);
                            cacheHit = true;
                            codegenCacheDecision = "hit";
                            cachedActivitiesLoaded = cachedBeans.size();
                        } else {
                            codegenCacheDecision = "keyMatchedButMissingCachedFiles";
                            cachedActivitiesLoaded = cachedBeans.size();
                        }
                    } else {
                        codegenCacheDecision = "cacheKeyChanged";
                    }
                } catch (RuntimeException e) {
                    codegenCacheDecision = "cacheReadFailed";
                    Log.e("ProjectFilePaths", "Failed to read code generation cache for project " + sc_id + " from " + cacheKeyFile.getAbsolutePath(), e);
                }
            }

            if (!cacheHit) {
                CommandBlock.clearTempCommands();
            }

            long codegenCacheLookupDuration = System.currentTimeMillis() - codegenCacheLookupStarted;
            int threadCount = 0;
            long codeGenerationDuration = 0;
            if (!cacheHit) {
                long codeGenerationStarted = System.currentTimeMillis();
                // Cache miss: generate code and save to cache
                codegenCacheDir.mkdirs();

                // Pre-build shared objects once for all Activities (optimization)
                ManageLocalLibrary sharedMll = new ManageLocalLibrary(projectDataManager.projectId);
                HashMap<String, Map<String, Object>> sharedExtraBlocksMap = ActivityCodeGenerator.buildExtraBlocksMap(getExtraBlockData());
                Material3LibraryManager sharedMaterialLibraryManager = new Material3LibraryManager(projectDataManager.projectId);

                // Pre-warm BlockLoader caches to avoid race conditions during parallel execution
                BlockLoader.getBlockFromProject(sc_id, "");

                threadCount = activitiesToGenerate.isEmpty() ? 0
                        : Math.min(Runtime.getRuntime().availableProcessors(), activitiesToGenerate.size());
                if (threadCount <= 1) {
                    for (ProjectFileBean activity : activitiesToGenerate) {
                        String phase1Code = new ActivityCodeGenerator(buildConfig, activity, projectDataManager,
                                sharedMll, projectSettings, sharedExtraBlocksMap, sharedMaterialLibraryManager)
                                .generateCode(isAndroidStudioExport, sc_id, false);
                        srcCodeBeans.add(new SrcCodeBean(activity.getJavaName(),
                                ActivityCodeGenerator.applyCommands(phase1Code)));
                        FileUtil.writeFile(new File(codegenCacheDir, activity.getJavaName() + ".code").getAbsolutePath(), phase1Code);
                    }
                } else {
                    ExecutorService executor = Executors.newFixedThreadPool(threadCount);
                    try {
                        List<Future<Pair<String, String>>> futures = new ArrayList<>();

                        for (ProjectFileBean activity : activitiesToGenerate) {
                            futures.add(executor.submit(() -> {
                                String rawCode = new ActivityCodeGenerator(buildConfig, activity, projectDataManager,
                                        sharedMll, projectSettings, sharedExtraBlocksMap, sharedMaterialLibraryManager)
                                        .generateCode(isAndroidStudioExport, sc_id, false);
                                return new Pair<>(activity.getJavaName(), rawCode);
                            }));
                        }

                        // Phase 2: Apply command blocks serially (CommandBlock is not thread-safe)
                        for (int i = 0; i < futures.size(); i++) {
                            try {
                                Pair<String, String> result = futures.get(i).get();
                                srcCodeBeans.add(new SrcCodeBean(result.first,
                                        ActivityCodeGenerator.applyCommands(result.second)));
                                FileUtil.writeFile(new File(codegenCacheDir, result.first + ".code").getAbsolutePath(), result.second);
                            } catch (InterruptedException | ExecutionException | RuntimeException e) {
                                if (e instanceof InterruptedException) {
                                    Thread.currentThread().interrupt();
                                }
                                ProjectFileBean activity = activitiesToGenerate.get(i);
                                Log.e("ProjectFilePaths", "Parallel code generation failed for " + activity.getJavaName() + " in project " + sc_id + "; falling back to serial generation", e);
                                String phase1Code = new ActivityCodeGenerator(buildConfig, activity, projectDataManager,
                                        sharedMll, projectSettings, sharedExtraBlocksMap, sharedMaterialLibraryManager)
                                        .generateCode(isAndroidStudioExport, sc_id, false);
                                srcCodeBeans.add(new SrcCodeBean(activity.getJavaName(),
                                        ActivityCodeGenerator.applyCommands(phase1Code)));
                                FileUtil.writeFile(new File(codegenCacheDir, activity.getJavaName() + ".code").getAbsolutePath(), phase1Code);
                            }
                        }
                    } finally {
                        executor.shutdownNow();
                    }
                }
                // Save cache key after successful generation
                FileUtil.writeFile(cacheKeyFile.getAbsolutePath(), cacheKey);
                codeGenerationDuration = System.currentTimeMillis() - codeGenerationStarted;
            }

            var path = SketchwarePaths.getProjectCommandPath(sc_id);
            var newXMLCommand = Boolean.parseBoolean(projectSettings.getValue(ProjectSettings.SETTING_NEW_XML_COMMAND, ProjectSettings.SETTING_GENERIC_VALUE_FALSE));
            if (newXMLCommand && FileUtil.isExistFile(path)) {
                FileUtil.copyFile(path, SketchwarePaths.getTempCommandsPath());
            }

            var viewBindingBuilder = new ViewBindingBuilder(List.of(), new File("."), packageName);

            // Generate layouts unless a custom version of it exists already
            // at /Internal storage/.sketchware/data/<sc_id>/files/resource/layout/
            ArrayList<ProjectFileBean> regularLayouts = projectFileManager.getActivities();
            for (ProjectFileBean layout : regularLayouts) {
                String xmlName = layout.getXmlName();
                LayoutGenerator layoutGenerator = new LayoutGenerator(buildConfig, layout);
                layoutGenerator.setViews(ProjectDataStore.getSortedRootViews(projectDataManager.getViews(xmlName)), projectDataManager.getFabView(xmlName));
                var ogFile = new File(layoutDir + xmlName);
                if (!layoutFiles.contains(ogFile)) {
                    srcCodeBeans.add(new SrcCodeBean(xmlName, CommandBlock.applyCommands(xmlName, layoutGenerator.toXmlString())));

                    if (isViewBindingEnable()) {
                        var privFile = new File(context.getCacheDir(), xmlName);
                        FileUtil.writeFile(privFile.getAbsolutePath(), CommandBlock.applyCommands(xmlName, layoutGenerator.toXmlString()));
                        var code = viewBindingBuilder.generateBindingForLayout(privFile);
                        srcCodeBeans.add(new SrcCodeBean(
                                ViewBindingBuilder.generateFileNameForLayout(xmlName.replace(".xml", "")) + ".java",
                                code
                        ));
                    }
                }
            }

            ArrayList<ProjectFileBean> customViewFiles = projectFileManager.getCustomViews();
            for (ProjectFileBean customViewFile : customViewFiles) {
                String xmlName = customViewFile.getXmlName();
                LayoutGenerator layoutGenerator = new LayoutGenerator(buildConfig, customViewFile);
                layoutGenerator.setViews(ProjectDataStore.getSortedRootViews(projectDataManager.getViews(xmlName)));
                var ogFile = new File(layoutDir + xmlName);
                if (!layoutFiles.contains(ogFile)) {
                    srcCodeBeans.add(new SrcCodeBean(xmlName, CommandBlock.applyCommands(xmlName, layoutGenerator.toXmlString())));

                    if (isViewBindingEnable()) {
                        var privFile = new File(context.getCacheDir(), xmlName);
                        FileUtil.writeFile(privFile.getAbsolutePath(), CommandBlock.applyCommands(xmlName, layoutGenerator.toXmlString()));
                        var code = viewBindingBuilder.generateBindingForLayout(privFile);
                        srcCodeBeans.add(new SrcCodeBean(
                                ViewBindingBuilder.generateFileNameForLayout(xmlName.replace(".xml", "")) + ".java",
                                code
                        ));
                    }
                }
            }

            ManifestGenerator manifestGenerator = new ManifestGenerator(buildConfig, projectFileManager.getActivities(), builtInLibraryManager);
            manifestGenerator.setProjectFilePaths(this);

            // Make generated classes viewable
            if (!javaFiles.contains(new File(javaDir + "SketchwareUtil.java"))) {
                srcCodeBeans.add(new SrcCodeBean("SketchwareUtil.java",
                        ComponentTemplates.getSketchwareUtilCode(packageName, material3LibraryManager.isMaterial3Enabled())));
            }

            if (!javaFiles.contains(new File(javaDir + "FileUtil.java"))) {
                srcCodeBeans.add(new SrcCodeBean("FileUtil.java",
                        ComponentTemplates.getFileUtilCode(packageName)));
            }

            if (!javaFiles.contains(new File(javaDir + "RequestNetwork.java")) && buildConfig.isHttp3Used) {
                srcCodeBeans.add(new SrcCodeBean("RequestNetwork.java",
                        ComponentCodeGenerator.formatCode(ComponentTemplates.getRequestNetworkCode(packageName), false)));
            }

            if (!FileUtil.isExistFile(javaDir + "RequestNetworkController.java") && buildConfig.isHttp3Used) {
                srcCodeBeans.add(new SrcCodeBean("RequestNetworkController.java",
                        ComponentCodeGenerator.formatCode(ComponentTemplates.getRequestNetworkControllerCode(packageName), false)));
            }

            if (!javaFiles.contains(new File(javaDir + "BluetoothConnect.java")) && buildConfig.hasPermission(BuildConfig.PERMISSION_BLUETOOTH)) {
                srcCodeBeans.add(new SrcCodeBean("BluetoothConnect.java",
                        ComponentCodeGenerator.formatCode(ComponentTemplates.getBluetoothConnectCode(packageName), false)));
            }

            if (!javaFiles.contains(new File(javaDir + "BluetoothController.java")) && buildConfig.hasPermission(BuildConfig.PERMISSION_BLUETOOTH)) {
                srcCodeBeans.add(new SrcCodeBean("BluetoothController.java",
                        ComponentCodeGenerator.formatCode(ComponentTemplates.getBluetoothControllerCode(packageName), false)));
            }

            if (buildConfig.isMapUsed) {
                if (!javaFiles.contains(new File(javaDir + "GoogleMapController.java")) && buildConfig.isMapUsed) {
                    srcCodeBeans.add(new SrcCodeBean("GoogleMapController.java",
                            ComponentCodeGenerator.formatCode(ComponentTemplates.getGoogleMapControllerCode(packageName), false)));
                }
            }

            String generatedManifest = finalizeGeneratedManifest(manifestGenerator.generateManifest());
            srcCodeBeans.add(new SrcCodeBean("AndroidManifest.xml", generatedManifest));
            srcCodeBeans.add(new SrcCodeBean("styles.xml", getXMLStyle()));
            srcCodeBeans.add(new SrcCodeBean("colors.xml", getXMLColor()));
            srcCodeBeans.add(new SrcCodeBean("strings.xml", getXMLString()));
            Log.d("ProjectFilePaths", "generateSourceCodeBeans: activitiesToGenerate=" + activitiesToGenerate.size()
                    + ", cache=" + codegenCacheDecision
                    + ", cachedActivitiesLoaded=" + cachedActivitiesLoaded
                    + ", missingCachedFiles=" + missingCachedFiles
                    + ", cacheLookup=" + codegenCacheLookupDuration + " ms"
                    + ", codeGeneration=" + codeGenerationDuration + " ms"
                    + ", threadCount=" + threadCount
                    + ", viewBindingEnabled=" + isViewBindingEnable()
                    + ", cacheKeyHash=" + cacheKeyHash
                    + ", totalBeans=" + srcCodeBeans.size()
                    + ", total=" + (System.currentTimeMillis() - generateSourceCodeBeansStarted) + " ms");
            return srcCodeBeans;
        } finally {
            CommandBlock.clearTempCommands();
        }
    }

    private boolean isViewBindingEnable() {
        return generateDataBindingClasses && projectSettings.getValue(ProjectSettings.SETTING_ENABLE_VIEWBINDING, ProjectSettings.SETTING_GENERIC_VALUE_FALSE).equals(ProjectSettings.SETTING_GENERIC_VALUE_TRUE);
    }

    /**
     * Get generated source code of a file.
     *
     * @return The file's code or an empty String if not found
     */
    public String getFileSrc(String filename, ProjectFileManager projectFileManager, ProjectDataStore projectDataManager, LibraryManager projectLibraryManager) {
        initializeMetadata(projectLibraryManager, projectFileManager, projectDataManager);
        CommandBlock.clearTempCommands();
        try {
            boolean isJavaFile = filename.endsWith(".java");
            boolean isXmlFile = filename.endsWith(".xml");
            boolean isManifestFile = filename.equals("AndroidManifest.xml");
            ArrayList<ProjectFileBean> projectFiles = new ArrayList<>(projectFileManager.getActivities());
            projectFiles.addAll(new ArrayList<>(projectFileManager.getCustomViews()));
            if (isXmlFile) {
                /*
                 Generating every java file is necessary to make command blocks for xml work
                 */
                prepareXmlCommands(projectFileManager, projectDataManager);
            }

            switch (filename) {
                case "strings.xml" -> {
                    return getXMLString();
                }
                case "colors.xml" -> {
                    return getXMLColor();
                }
                case "styles.xml" -> {
                    return getXMLStyle();
                }
            }

            if (isManifestFile) {
                ProjectBuilder builder = new ProjectBuilder(SketchApplication.getAppContext(), this);
                builder.buildBuiltInLibraryInformation();
                ManifestGenerator manifestGenerator = new ManifestGenerator(buildConfig, projectFileManager.getActivities(), builder.getBuiltInLibraryManager());
                manifestGenerator.setProjectFilePaths(this);
                return finalizeGeneratedManifest(manifestGenerator.generateManifest());
            }

            for (ProjectFileBean projectFile : projectFiles) {
                if (filename.equals(isJavaFile ? projectFile.getJavaName() : projectFile.getXmlName())) {
                    if (isJavaFile) {
                        return new ActivityCodeGenerator(buildConfig, projectFile, projectDataManager).generateCode(isAndroidStudioExport, sc_id);
                    } else if (isXmlFile) {
                        LayoutGenerator xmlGenerator = new LayoutGenerator(buildConfig, projectFile);
                        xmlGenerator.setViews(ProjectDataStore.getSortedRootViews(projectDataManager.getViews(filename)), projectDataManager.getFabView(filename));
                        return CommandBlock.applyCommands(filename, xmlGenerator.toXmlString());
                    }
                }
            }

            return "";
        } finally {
            CommandBlock.clearTempCommands();
        }
    }

    private void prepareXmlCommands(ProjectFileManager projectFileManager, ProjectDataStore projectDataManager) {
        ArrayList<ProjectFileBean> projectFiles = new ArrayList<>(projectFileManager.getActivities());
        projectFiles.addAll(new ArrayList<>(projectFileManager.getCustomViews()));
        String commandFilePath = SketchwarePaths.getProjectCommandPath(sc_id);
        boolean newXMLCommand = Boolean.parseBoolean(projectSettings.getValue(ProjectSettings.SETTING_NEW_XML_COMMAND, ProjectSettings.SETTING_GENERIC_VALUE_FALSE));
        if (newXMLCommand && FileUtil.isExistFile(commandFilePath)) {
            FileUtil.copyFile(commandFilePath, SketchwarePaths.getTempCommandsPath());
        } else {
            for (ProjectFileBean projectFile : projectFiles) {
                try {
                    CommandBlock.collectXmlCommandBlocks(new ActivityCodeGenerator(buildConfig, projectFile, projectDataManager).generateCode(isAndroidStudioExport, sc_id, false));
                } catch (RuntimeException e) {
                    Log.e("ProjectFilePaths", "Failed to prepare XML commands", e);
                }
            }
        }
    }

    public String getXMLString() {
        String filePath = SketchwarePaths.getProjectResourceValuesFilePath(sc_id, "strings.xml");
        if (FileUtil.isExistFile(filePath) && exportingType == ExportType.SOURCE_CODE_VIEWING) {
            return FileUtil.readFile(filePath);
        }
        XmlBuilderHelper stringsFileBuilder = new XmlBuilderHelper();
        stringsFileBuilder.addNonTranslatableString("app_name", applicationName);
        return applyStoredXmlCommandsIfNeeded("strings.xml", stringsFileBuilder.toCode());
    }

    public String getXMLColor() {
        String filePath = SketchwarePaths.getProjectResourceValuesFilePath(sc_id, "colors.xml");
        if (FileUtil.isExistFile(filePath) && exportingType == ExportType.SOURCE_CODE_VIEWING) {
            return FileUtil.readFile(filePath);
        }
        XmlBuilderHelper colorsFileBuilder = new XmlBuilderHelper();
        colorsFileBuilder.addColor("colorPrimary", String.format("#%06X", colorPrimary & 0xffffff));
        colorsFileBuilder.addColor("colorPrimaryDark", String.format("#%06X", colorPrimaryDark & 0xffffff));
        colorsFileBuilder.addColor("colorAccent", String.format("#%06X", colorAccent & 0xffffff));
        colorsFileBuilder.addColor("colorControlHighlight", String.format("#%06X", colorControlHighlight & 0xffffff));
        colorsFileBuilder.addColor("colorControlNormal", String.format("#%06X", colorControlNormal & 0xffffff));
        return applyStoredXmlCommandsIfNeeded("colors.xml", colorsFileBuilder.toCode());
    }

    public String getXMLStyle() {
        String filePath = SketchwarePaths.getProjectResourceValuesFilePath(sc_id, "styles.xml");
        if (FileUtil.isExistFile(filePath) && exportingType == ExportType.SOURCE_CODE_VIEWING) {
            return FileUtil.readFile(filePath);
        }
        if (material3LibraryManager.isMaterial3Enabled()) {
            XmlBuilderHelper stylesFileBuilder = new XmlBuilderHelper();
            stylesFileBuilder.addStyle("AppTheme", String.format("Theme.Material3.%s.NoActionBar", material3LibraryManager.getTheme()));
            stylesFileBuilder.addItemToStyle("AppTheme", "android:statusBarColor", "@android:color/transparent");
            stylesFileBuilder.addItemToStyle("AppTheme", "android:navigationBarColor", "@android:color/transparent");
            stylesFileBuilder.addItemToStyle("AppTheme", "android:windowLightStatusBar", "?attr/isLightTheme");
            stylesFileBuilder.addStyle("AppTheme.FullScreen", "AppTheme");
            stylesFileBuilder.addItemToStyle("AppTheme.FullScreen", "android:windowFullscreen", "true");
            stylesFileBuilder.addItemToStyle("AppTheme.FullScreen", "android:windowContentOverlay", "@null");
            stylesFileBuilder.addStyle("AppTheme.AppBarOverlay", "ThemeOverlay.Material3");
            stylesFileBuilder.addStyle("AppTheme.PopupOverlay", "ThemeOverlay.Material3");
            stylesFileBuilder.addStyle("AppTheme.DebugActivity", "AppTheme");
            stylesFileBuilder.addItemToStyle("AppTheme.DebugActivity", "windowActionBar", "true");
            stylesFileBuilder.addItemToStyle("AppTheme.DebugActivity", "windowNoTitle", "false");
            return applyStoredXmlCommandsIfNeeded("styles.xml", stylesFileBuilder.toCode());
        } else if (buildConfig.isAppCompatEnabled) {
            boolean useNewMaterialComponentsTheme = projectSettings.getValue(ProjectSettings.SETTING_ENABLE_BRIDGELESS_THEMES,
                    BuildSettings.SETTING_GENERIC_VALUE_FALSE).equals(BuildSettings.SETTING_GENERIC_VALUE_TRUE);
            XmlBuilderHelper stylesFileBuilder = new XmlBuilderHelper();
            stylesFileBuilder.addStyle("AppTheme", "Theme.MaterialComponents.Light.NoActionBar" + (useNewMaterialComponentsTheme ? "" : ".Bridge"));
            // todo: add 'colorOnPrimary' to custom theme colors.
            stylesFileBuilder.addItemToStyle("AppTheme", "colorOnPrimary", "@android:color/white");
            stylesFileBuilder.addItemToStyle("AppTheme", "colorPrimary", "@color/colorPrimary");
            stylesFileBuilder.addItemToStyle("AppTheme", "colorPrimaryDark", "@color/colorPrimaryDark");
            stylesFileBuilder.addItemToStyle("AppTheme", "colorAccent", "@color/colorAccent");
            stylesFileBuilder.addItemToStyle("AppTheme", "colorControlHighlight", "@color/colorControlHighlight");
            stylesFileBuilder.addItemToStyle("AppTheme", "colorControlNormal", "@color/colorControlNormal");

            stylesFileBuilder.addStyle("AppTheme.FullScreen", "AppTheme");
            stylesFileBuilder.addItemToStyle("AppTheme.FullScreen", "android:windowFullscreen", "true");
            stylesFileBuilder.addItemToStyle("AppTheme.FullScreen", "android:windowContentOverlay", "@null");

            stylesFileBuilder.addStyle("AppTheme.AppBarOverlay", "ThemeOverlay.MaterialComponents.Dark.ActionBar");
            stylesFileBuilder.addStyle("AppTheme.PopupOverlay", "ThemeOverlay.MaterialComponents.Light");

            stylesFileBuilder.addStyle("AppTheme.DebugActivity", "AppTheme");
            stylesFileBuilder.addItemToStyle("AppTheme.DebugActivity", "actionBarStyle", "@style/ThemeOverlay.MaterialComponents.ActionBar.Primary");
            stylesFileBuilder.addItemToStyle("AppTheme.DebugActivity", "actionBarTheme", "@style/Widget.MaterialComponents.ActionBar.Primary");
            stylesFileBuilder.addItemToStyle("AppTheme.DebugActivity", "windowActionBar", "true");
            stylesFileBuilder.addItemToStyle("AppTheme.DebugActivity", "windowNoTitle", "false");
            return applyStoredXmlCommandsIfNeeded("styles.xml", stylesFileBuilder.toCode());
        } else {
            XmlBuilderHelper stylesFileBuilder = new XmlBuilderHelper();
            stylesFileBuilder.addStyle("AppTheme", "@android:style/Theme.Material.Light.DarkActionBar");
            stylesFileBuilder.addItemToStyle("AppTheme", "android:colorPrimary", "@color/colorPrimary");
            stylesFileBuilder.addItemToStyle("AppTheme", "android:colorPrimaryDark", "@color/colorPrimaryDark");
            stylesFileBuilder.addItemToStyle("AppTheme", "android:colorAccent", "@color/colorAccent");
            stylesFileBuilder.addItemToStyle("AppTheme", "android:colorControlHighlight", "@color/colorControlHighlight");
            stylesFileBuilder.addItemToStyle("AppTheme", "android:colorControlNormal", "@color/colorControlNormal");
            stylesFileBuilder.addStyle("FullScreen", "@android:style/Theme.Material.Light.NoActionBar.Fullscreen");
            stylesFileBuilder.addItemToStyle("FullScreen", "android:colorPrimary", "@color/colorPrimary");
            stylesFileBuilder.addItemToStyle("FullScreen", "android:colorPrimaryDark", "@color/colorPrimaryDark");
            stylesFileBuilder.addItemToStyle("FullScreen", "android:colorAccent", "@color/colorAccent");
            stylesFileBuilder.addItemToStyle("FullScreen", "android:colorControlHighlight", "@color/colorControlHighlight");
            stylesFileBuilder.addItemToStyle("FullScreen", "android:colorControlNormal", "@color/colorControlNormal");
            stylesFileBuilder.addStyle("NoActionBar", "@android:style/Theme.Material.Light.NoActionBar");
            stylesFileBuilder.addItemToStyle("NoActionBar", "android:colorPrimary", "@color/colorPrimary");
            stylesFileBuilder.addItemToStyle("NoActionBar", "android:colorPrimaryDark", "@color/colorPrimaryDark");
            stylesFileBuilder.addItemToStyle("NoActionBar", "android:colorAccent", "@color/colorAccent");
            stylesFileBuilder.addItemToStyle("NoActionBar", "android:colorControlHighlight", "@color/colorControlHighlight");
            stylesFileBuilder.addItemToStyle("NoActionBar", "android:colorControlNormal", "@color/colorControlNormal");
            stylesFileBuilder.addStyle("NoStatusBar", "AppTheme");
            stylesFileBuilder.addItemToStyle("NoStatusBar", "android:windowFullscreen", "true");
            stylesFileBuilder.addStyle("AppTheme.DebugActivity", "AppTheme");
            return applyStoredXmlCommandsIfNeeded("styles.xml", stylesFileBuilder.toCode());
        }
    }

    private String applyStoredXmlCommandsIfNeeded(String fileName, String sourceCode) {
        String tempCommandPath = SketchwarePaths.getTempCommandsPath();
        if (CommandBlock.hasTempCommands()) {
            return CommandBlock.applyCommands(fileName, sourceCode);
        }

        boolean newXMLCommand = Boolean.parseBoolean(projectSettings.getValue(ProjectSettings.SETTING_NEW_XML_COMMAND, ProjectSettings.SETTING_GENERIC_VALUE_FALSE));
        String storedCommandPath = SketchwarePaths.getProjectCommandPath(sc_id);
        if (!newXMLCommand || !FileUtil.isExistFile(storedCommandPath)) {
            return CommandBlock.applyCommands(fileName, sourceCode);
        }

        CommandBlock.clearTempCommands();
        try {
            FileUtil.copyFile(storedCommandPath, tempCommandPath);
            return CommandBlock.applyCommands(fileName, sourceCode);
        } finally {
            CommandBlock.clearTempCommands();
        }
    }

    private boolean isLocalLibraryManifestMergeEnabled() {
        return ProjectSettings.SETTING_GENERIC_VALUE_TRUE.equals(
                projectSettings.getValue(
                        ProjectSettings.SETTING_ENABLE_LOCAL_LIBRARY_MANIFEST_MERGE,
                        ProjectSettings.SETTING_GENERIC_VALUE_FALSE));
    }

    private String finalizeGeneratedManifest(String sourceCode) {
        String manifest = AndroidManifestInjector.injectCustomComponents(sourceCode, sc_id);
        manifest = manifest.replace("${applicationId}", packageName);
        if (isLocalLibraryManifestMergeEnabled() && !isAndroidStudioExport) {
            manifest = LocalLibraryManifestMerger.mergeLocalLibraryManifests(manifest, sc_id, packageName);
        }
        return applyStoredXmlCommandsIfNeeded("AndroidManifest.xml", manifest);
    }

    /**
     * Computes a cache key for code generation based on all input data files and settings.
     * If any input changes, the key changes and cached code is invalidated.
     */
    private String computeCodeGenCacheKey(ProjectFileManager projectFileManager, ProjectDataStore projectDataManager, LibraryManager projectLibraryManager) {
        StringBuilder key = new StringBuilder(256);

        String dataPath = SketchwarePaths.getDataPath(sc_id);

        try {
            if (projectDataManager != null) {
                StringBuilder logicBuffer = new StringBuilder();
                projectDataManager.serializeLogicData(logicBuffer);
                appendTextInfo(key, logicBuffer);
            } else {
                appendFileInfo(key, new File(dataPath, "logic"));
            }
        } catch (RuntimeException e) {
            Log.w("ProjectFilePaths", "Falling back to on-disk logic signature for project " + sc_id, e);
            appendFileInfo(key, new File(dataPath, "logic"));
        }

        try {
            if (projectDataManager != null) {
                StringBuilder viewBuffer = new StringBuilder();
                projectDataManager.serializeViewData(viewBuffer);
                appendTextInfo(key, viewBuffer);
            } else {
                appendFileInfo(key, new File(dataPath, "view"));
            }
        } catch (RuntimeException e) {
            Log.w("ProjectFilePaths", "Falling back to on-disk view signature for project " + sc_id, e);
            appendFileInfo(key, new File(dataPath, "view"));
        }

        try {
            if (projectFileManager != null) {
                StringBuilder fileBuffer = new StringBuilder();
                projectFileManager.serializeFiles(fileBuffer);
                appendTextInfo(key, fileBuffer);
            } else {
                appendFileInfo(key, new File(dataPath, "file"));
            }
        } catch (RuntimeException e) {
            Log.w("ProjectFilePaths", "Falling back to on-disk file signature for project " + sc_id, e);
            appendFileInfo(key, new File(dataPath, "file"));
        }

        try {
            if (projectLibraryManager != null) {
                StringBuilder libraryBuffer = new StringBuilder();
                projectLibraryManager.serializeLibraries(libraryBuffer);
                appendTextInfo(key, libraryBuffer);
            } else {
                appendFileInfo(key, new File(dataPath, "library"));
            }
        } catch (RuntimeException e) {
            Log.w("ProjectFilePaths", "Falling back to on-disk library signature for project " + sc_id, e);
            appendFileInfo(key, new File(dataPath, "library"));
        }

        boolean localLibraryManifestMergeEnabled = isLocalLibraryManifestMergeEnabled();
        appendTextInfo(key, localLibraryManifestMergeEnabled
                ? ProjectSettings.SETTING_GENERIC_VALUE_TRUE
                : ProjectSettings.SETTING_GENERIC_VALUE_FALSE);
        appendFileInfo(key, new File(dataPath, "local_library"));
        if (localLibraryManifestMergeEnabled) {
            try {
                for (String manifestPath : new ManageLocalLibrary(sc_id).getManifestPaths()) {
                    appendFileInfo(key, new File(manifestPath));
                }
            } catch (RuntimeException e) {
                Log.w("ProjectFilePaths", "Failed to append local library manifest signatures for project " + sc_id, e);
            }
        }

        appendFileInfo(key, new File(dataPath, "project_config"));

        appendFileInfo(key, ExtraBlockFile.EXTRA_BLOCKS_DATA_FILE);

        appendFileInfo(key, new File(dataPath, "custom_blocks"));

        appendFileInfo(key, new File(EventsHandler.CUSTOM_EVENTS_FILE_PATH));
        appendFileInfo(key, new File(EventsHandler.CUSTOM_LISTENER_FILE_PATH));
        appendFileInfo(key, new File(SketchwarePaths.getAbsolutePathOf(SketchwarePaths.CUSTOM_COMPONENT_FILE)));

        key.append(isAndroidStudioExport ? '1' : '0');
        appendTextInfo(key, packageName);

        try {
            Context ctx = SketchApplication.getAppContext();
            PackageInfo pkgInfo = ctx.getPackageManager().getPackageInfo(ctx.getPackageName(), 0);
            key.append('|').append(pkgInfo.versionCode).append('|').append(pkgInfo.lastUpdateTime);
        } catch (PackageManager.NameNotFoundException ignored) {
        }

        return key.toString();
    }

    private static void appendTextInfo(StringBuilder key, CharSequence text) {
        byte[] bytes = text == null ? new byte[0] : text.toString().getBytes(StandardCharsets.UTF_8);
        CRC32 crc = new CRC32();
        crc.update(bytes, 0, bytes.length);
        key.append(crc.getValue()).append('|').append(bytes.length).append('|');
    }

    private static void appendFileInfo(StringBuilder key, File file) {
        if (file.exists()) {
            try {
                CRC32 crc = new CRC32();
                byte[] buffer = new byte[8192];
                try (FileInputStream fis = new FileInputStream(file)) {
                    int bytesRead;
                    while ((bytesRead = fis.read(buffer)) != -1) {
                        crc.update(buffer, 0, bytesRead);
                    }
                }
                key.append(crc.getValue()).append('|').append(file.length()).append('|');
            } catch (IOException e) {
                key.append(file.lastModified()).append('|').append(file.length()).append('|');
            }
        } else {
            key.append("0|0|");
        }
    }

    public enum ExportType {
        AAB,
        SIGN_APP,
        DEBUG_APP,
        ANDROID_STUDIO,
        SOURCE_CODE_VIEWING
    }
}
